import type { Mnemonics } from '../types';

// Mnemotecnias: caracter → frase para recordar lectura/trazo.
export const MN: Mnemonics = {
  // ── HIRAGANA — Catálogo Maestro ─────────────────────────────
  あ: "Una antena de radio sobre una cruz. Alguien grita '¡Aaa!' al recibir señal.",
  い: 'Dos anguilas verticales. O las orejas de un perro (inu = いぬ).',
  う: "Un hombre cargando una bolsa pesada sobre su espalda doblada: '¡Uuu!'",
  え: 'Un ave exótica con una pluma larga. O una escalera mecánica.',
  お: "Un jugador de golf golpeando una bola. O alguien gritando '¡Oh!'",
  か: 'Una patada de karate con pierna extendida y brazo en guardia.',
  き: 'La parte superior de una llave antigua (key) con sus dientes.',
  く: 'El pico de un pájaro cuco abierto. O un cuervo (ku-erbo).',
  け: 'Un barril de sake. O una persona practicando Kendo.',
  こ: 'Dos gusanos o lados de una mazorca de maíz (corncob) descansando.',
  さ: 'Una antena parabólica (satélite) recibiendo ondas del espacio.',
  し: 'Ella (she) tiene el pelo muy largo que se curva al final.',
  す: "Un columpio girando. O alguien que dice '¡Sss-sushi!'",
  せ: "Un hombre sentado en un sofá diciendo '¡Se-ntado!'",
  そ: "Una costura en zigzag. '¡Soooo many zigzags!'",
  た: 'Los trazos forman literalmente las letras T y a inclinadas.',
  ち: "Una cara con una barbilla enorme. O '5' centavos (cheap).",
  つ: 'Una gran ola de un tsunami rompiendo hacia la derecha.',
  て: 'Un telescopio apuntando hacia arriba. O una mano (te = mano en japonés).',
  と: 'Un dedo del pie (toe) con una astilla clavada.',
  な: 'Una monja (nan) arrodillada frente a una cruz.',
  に: 'Una rodilla (ni-rodilla) doblada. O dos agujas de coser paralelas.',
  ぬ: 'Un nudo complejo. O fideos (noodles) enredados en palillos.',
  ね: 'Un gato (neko) con la cola rizada. O una red de pescar.',
  の: "Una señal de prohibido. O simplemente 'No' dentro de un círculo.",
  は: "Una silla junto a una persona riendo: '¡Ha, ha, ha!'",
  ひ: 'Una sonrisa amplia (hi-risa). O el perfil de una nariz y boca.',
  ふ: 'El monte Fuji visto desde arriba. O el bigote de Fu Manchú.',
  へ: 'Una montaña pequeña. O un pajar de heno (heno en japonés).',
  ほ: "Un hombre con sombrero mirando una fogata. '¡Ho ho ho!'",
  ま: 'Una mamá con los brazos abiertos. O el mástil de un barco.',
  み: "Un gancho para carne. O alguien gritando '¡Mi-ra!'",
  む: "Una vaca mugiendo '¡Muu!' con sus cuernos visibles.",
  め: 'Un ojo con una pestaña. Me = ojo en japonés.',
  も: "Un anzuelo con dos líneas de carnada: '¡Mo-re fish!'",
  や: 'Un yak con dos cuernos grandes mirando al frente.',
  ゆ: 'Un pez único nadando. O un submarino (U-boat).',
  よ: "Un hombre haciendo señas con la mano diciendo '¡Yo!'",
  ら: 'Un conejo (rabbit) saltando sobre un obstáculo.',
  り: 'Dos juncos al borde de un río. O un anillo (ring).',
  る: 'Un camino con un rizo al final que lleva a un rubí.',
  れ: 'Un hombre descansando contra un árbol. O un reptil.',
  ろ: "Igual que る, pero el rubí se ha caído: '¡Ro-dó!'",
  わ: 'Un avispero (avispero) en una pared. O el agua rompiendo.',
  を: "Un hombre cruzando una barrera. '¡Wou!' al caer en un hoyo. Solo vive como partícula de objeto.",
  ん: 'Una letra n cursiva. O un avión volando hacia abajo. La única consonante sola del japonés.',
  // Dakuon
  が: 'か + tenten. K→G. Karate se vuelve más grave y sonoro.',
  ぎ: 'き + tenten. Ki→Gi. La llave ahora abre algo más pesado.',
  ぐ: 'く + tenten. Ku→Gu. El cuervo ahora grazna más grave.',
  げ: 'け + tenten. Ke→Ge. El barril de sake se vuelve genki.',
  ご: 'こ + tenten. Ko→Go. Los gusanos ahora se mueven con fuerza.',
  ざ: 'さ + tenten. Sa→Za. La antena capta señales con zumbido.',
  じ: 'し + tenten. Shi→Ji. El pelo largo vibra con energía. Muy frecuente: jikan (時間, tiempo).',
  ず: 'す + tenten. Su→Zu. El columpio zumba al girar.',
  ぜ: 'せ + tenten. Se→Ze. El sofá zen ahora vibra.',
  ぞ: 'そ + tenten. So→Zo. El zigzag ahora tiene más fuerza.',
  だ: 'た + tenten. Ta→Da. La T y la a ahora golpean más fuerte.',
  ぢ: 'ち + tenten. Chi→Di. La barbilla da un golpe.',
  づ: 'つ + tenten. Tsu→Du. El tsunami doble.',
  で: 'て + tenten. Te→De. El telescopio detecta señales. Partícula muy usada en gramática.',
  ど: 'と + tenten. To→Do. La astilla duele más. Doko = dónde.',
  ば: 'は + tenten. Ha→Ba. La risa se vuelve grave. Baka empieza con ば.',
  び: 'ひ + tenten. Hi→Bi. La sonrisa es ahora más intensa.',
  ぶ: 'ふ + tenten. Fu→Bu. El Fuji ahora retumba.',
  べ: 'へ + tenten. He→Be. La montaña de heno retumba.',
  ぼ: 'ほ + tenten. Ho→Bo. El sombrero del hombre cae con fuerza. Boku (yo, masculino).',
  // Handakuon
  ぱ: "は + maru. Ha→Pa. El maru es como una pelota que hace '¡Pa!'",
  ぴ: "ひ + maru. Hi→Pi. La sonrisa hace '¡Pi-pi!'",
  ぷ: "ふ + maru. Fu→Pu. El Fuji suelta un '¡Pu!'",
  ぺ: 'へ + maru. He→Pe. La montaña tiene una pelota encima.',
  ぽ: "ほ + maru. Ho→Po. El sombrero sale disparado: '¡Po!'",
  // Youon
  きゃ: 'き + ya pequeño. Kya = un solo golpe. La llave gira rápido.',
  しゃ: 'し + ya pequeño. Sha. Como en sharingan — un solo sonido.',
  ちゃ: 'ち + ya pequeño. Cha. Como en ocha (té). Rápido y suave.',
  にゃ: 'に + ya pequeño. Nya. El sonido del gato. Nyan.',
  ひゃ: 'ひ + ya pequeño. Hya. La sonrisa se encoge.',
  みゃ: 'み + ya pequeño. Mya. El gancho gira veloz.',
  りゃ: 'り + ya pequeño. Rya. El anillo sale volando.',
  ぎゃ: 'ぎ + ya pequeño. Gya. Versión intensa de kya.',
  // Sokuon
  って: 'っ antes de て = pausa + te duplicado. Matte (espera) lo usa.',
  っか: 'っ antes de か = pausa + ka. Más enfático.',
  っぱ: 'っ antes de ぱ = pausa + pa. Surippa (pantuflas).',
  っさ: 'っ antes de さ = pausa + sa. Zasshi (revista).',
  // KATAKANA — diferenciación visual
  ア: 'Katakana. Airon (plancha). Forma angular de あ.',
  イ: 'Katakana. Inku (tinta). Dos trazos rectos como あ pero más angulares.',
  ウ: 'Katakana. Uinnaa (salchicha Viena). Tres trazos angulares.',
  エ: 'Katakana. Epuron (delantal). Parece una viga estructural. え más angular.',
  オ: 'Katakana. Ootobai (motocicleta). お con más fuerza.',
  カ: 'Katakana. Kamera (cámara). Similar a か pero sin trazo extra.',
  キ: 'Katakana. Kiroguramu (kilogramo). Llave más angular.',
  ク: 'Katakana. Kureyon (crayón). く con ángulo más pronunciado.',
  ケ: 'Katakana. Keeki (torta/pastel). け más recto.',
  コ: 'Katakana. Koohii (café). Parece una caja abierta hacia la izquierda.',
  サ: 'Katakana. Saboten (cactus). さ con forma de cacto.',
  シ: 'Katakana. Shiisoo (subibaja). CLAVE: Los trazos miran HACIA ARRIBA — como alguien esquiando cuesta arriba. ≠ ツ',
  ス: 'Katakana. Surippa (pantuflas). す más angular.',
  セ: 'Katakana. Seroteepu (cinta adhesiva). せ con forma de cinta.',
  ソ: 'Katakana. Sofa (sofá). CLAVE: Trazo largo casi vertical, mira HACIA ABAJO. ≠ ン',
  タ: 'Katakana. Taoru (toalla). た con ángulos más pronunciados.',
  チ: 'Katakana. Chiizu (queso). ち más geométrico.',
  ツ: 'Katakana. Tsuaa (tour). CLAVE: Los trazos miran HACIA ABAJO — aterrorizados por el tsunami que viene. ≠ シ',
  テ: 'Katakana. Tento (carpa de camping). て con trazos rectos.',
  ト: 'Katakana. Toranpu (cartas). と con forma de mástil.',
  ナ: 'Katakana. Naifu (cuchillo). な con forma de cuchillo.',
  ニ: 'Katakana. Nikoniko (sonrisa). Dos líneas paralelas = número 2 en kanji.',
  ヌ: 'Katakana. Nu — cruza como una X con cola.',
  ネ: 'Katakana. Nekutai (corbata). ね con forma de nudo de corbata.',
  ノ: 'Katakana. Nooto (cuaderno). Un solo trazo diagonal simple.',
  ハ: 'Katakana. Hangaa (percha). Dos líneas en V como una percha.',
  ヒ: 'Katakana. Hiitaa (estufa). ひ con trazo horizontal.',
  フ: 'Katakana. Furaipan (sartén). ふ reducido a un solo gancho.',
  ヘ: 'Katakana. Herumetto (casco). IDÉNTICO a he hiragana (へ). El único igual.',
  ホ: 'Katakana. Hottokeeki (hotcake). ほ con forma de cruz.',
  マ: 'Katakana. Mafuraa (bufanda). ま más angular.',
  ミ: 'Katakana. Minikaa (auto pequeño). Tres trazos diagonales.',
  ム: 'Katakana. Muudo (ánimo/mood). む reducido a forma angular.',
  メ: 'Katakana. Medaru (medalla). Parece una X inclinada.',
  モ: 'Katakana. Mootaabooto (barco a motor). も versión angular.',
  ヤ: 'Katakana. Taiya (neumático). や más recto.',
  ユ: 'Katakana. Yuufoo (OVNI). ゆ con forma de platillo volador.',
  ヨ: 'Katakana. Yooyoo (yoyó). Parece una E invertida.',
  ラ: 'Katakana. Raamen (ramen). ら con trazo recto.',
  リ: 'Katakana. Ribon (listón/moño). り más recto y elegante.',
  ル: 'Katakana. Rubii (rubí). る con ángulo más pronunciado.',
  レ: 'Katakana. Reinkooto (impermeable). Un solo trazo con gancho.',
  ロ: 'Katakana. Rooraasukeeto (patines). Un cuadrado perfecto.',
  ワ: 'Katakana. Waishatsu (camisa elegante). わ con forma de cuello.',
  ヲ: 'Katakana. Wotagei (baile de fans). Solo partícula de objeto.',
  ン: 'Katakana. Nunca inicia una palabra. CLAVE: Trazo largo HORIZONTAL. ≠ ソ (vertical).',
  // Días de la semana
  げつようび: 'Lunes = Luna (月). Recuerda: Getsuga Tenshou de Bleach.',
  かようび: 'Martes = Fuego (火). Katon no jutsu.',
  すいようび: 'Miércoles = Agua (水). Suiton de Kisame.',
  もくようび: 'Jueves = Madera (木). Mokuton de Yamato.',
  きんようび: 'Viernes = Oro (金). Fullmetal Alchemist.',
  どようび: 'Sábado = Tierra (土). Doton no jutsu.',
  にちようび: 'Domingo = Sol (日).',
  // Colores con mnemotecnia anime
  しろ: 'Blanco (shiro). Shirohige = Barba Blanca de One Piece.',
  くろ: 'Negro (kuro). Kurohige = Barba Negra. O Crow (cuervo).',
  みどり: 'Verde (midori). Izuku Midoriya — Deku de My Hero Academia.',
  あか: 'Rojo (aka). Akatsuki — la nube roja de Naruto.',
  あお: 'Azul (ao). Opening Blue Bird de Naruto.',
  きいろ: 'Amarillo (kiiro). Ki = llave dorada.',
  // Números (solo las que no colisionan con hiragana de otras lecciones:
  // に/さん/ご ya tienen mnemotecnia propia de trazo, se dejan intactas)
  いち: 'Ichi (1) = Ichigo Kurosaki de Bleach, el primer protagonista.',
  よん: 'Yon (4). Comparte sonido con "shi" (muerte) — por eso casi nadie dice shi, se prefiere yon.',
  ろく: 'Roku (6). Como una "roca" (rock) — sólido, directo, fácil de recordar.',
  なな: 'Nana (7) = Nana, la protagonista del manga/anime del mismo nombre. También se dice "shichi".',
  はち: 'Hachi (8) = Hachiko, el perro fiel. Ocho lados de lealtad esperando en la estación.',
  きゅう: 'Kyuu (9) = las nueve colas de Kurama, el Kyuubi de Naruto.',
  じゅう: 'Juu (10) = como en Jujutsu Kaisen — el sonido "ju" se repite dos veces.',
  // Kanji básicos (N5) — reusan los anclajes ya establecidos en las notas
  // de las lecciones de días/elementos, para que la mnemotecnia sea la
  // misma en todo el sílabo y no compita con otra versión.
  日: 'Nichi/hi = sol. Un cuadrado con una línea al medio — la ventana por donde entra el sol. Nichiyoubi = domingo.',
  月: 'Getsu/tsuki = luna. Una luna creciente estilizada dentro de un rectángulo. Getsuga Tenshou de Bleach.',
  火: 'Ka/hi = fuego. Llamas subiendo con chispas a los lados. El Katon no jutsu de Naruto.',
  水: 'Sui/mizu = agua. Una corriente central con salpicaduras — el Suiton de Kisame.',
  木: 'Moku/ki = árbol. Un tronco con raíces y ramas. El Mokuton de Yamato.',
  金: 'Kin/kane = oro/metal. Una montaña con un tesoro enterrado debajo. Fullmetal Alchemist.',
  土: 'Do/tsuchi = tierra. Una cruz sobre el suelo — el Doton no jutsu.',
  山: 'Yama = montaña. Tres picos dibujados literalmente, como el Monte Fuji.',
  川: 'Kawa = río. Tres trazos verticales — las corrientes de agua fluyendo.',
  人: 'Hito/jin = persona. Dos piernas caminando, como alguien visto de perfil.',
  大: 'Dai/oo = grande. Una persona con brazos y piernas bien extendidos — ¡lo más grande posible!',
  小: 'Shou/chii = pequeño. Tres trazos pequeños, como gotas diminutas.',
  中: 'Chuu/naka = dentro/centro. Una línea atravesando un cuadro justo por el medio.',
  一: 'Ichi = uno. Un solo trazo horizontal.',
  二: 'Ni = dos. Dos trazos horizontales.',
  三: 'San = tres. Tres trazos horizontales — como Sanji de One Piece contando con los dedos.',
  上: 'Ue/jou = arriba. Una línea base con un trazo apuntando hacia arriba.',
  下: 'Shita/ka = abajo. Una línea base con un trazo apuntando hacia abajo.',
};
