import type { Module } from '../types';

// Contenido: módulos, lecciones, caracteres y notas didácticas.
export const MODULES: Module[] = [
  {
    id: 'm1',
    levelNum: 1,
    levelTitle: 'Nivel 1: Fundamentos Absolutos',
    block: 'I',
    bLabel: 'Alfabetización y Fonética',
    title: 'Módulo 1',
    sub: 'Hiragana — El Código Nativo',
    color: '#8CF244',
    xpE: 200,
    lessons: [
      {
        id: 'm1l1',
        t: 'あ行',
        s: 'a · i · u · e · o',
        xp: 40,
        chars: ['あ', 'い', 'う', 'え', 'お'],
        reads: ['a', 'i', 'u', 'e', 'o'],
        note: 'Las 5 vocales puras. El japonés NO tiene diptongos — cada vocal es un sonido limpio e independiente. Elimina el romaji cuanto antes para no crear vicios de pronunciación.',
        objective: 'Dominar la pronunciación limpia de las 5 vocales puras y sus mnemotecnias iconográficas.',
        tables: [
          {
            title: 'Fila de las Vocales Puras (あ行)',
            headers: ['Kana', 'Romaji', 'Pronunciación', 'Mnemotecnia Visual', 'Ejemplo'],
            rows: [
              ['あ', 'a', 'Como "a" del español', 'Antena de radio con lazo cruzado', 'あめ (Lluvia/Dulce)'],
              ['い', 'i', 'Como "i" del español', 'Dos anguilas o dos "I" paralelas', 'いい (Bueno)'],
              ['う', 'u', 'Como "u" (labios relajados)', 'Persona cargando bolsa en espalda', 'うた (Canción)'],
              ['え', 'e', 'Como "e" del español', 'Gimnasta estirándose sobre barra', 'えん (Yen)'],
              ['お', 'o', 'Como "o" del español', 'Golfista haciendo tiro de salida', 'おいしい (Delicioso)'],
            ],
          },
        ],
        pitchNote: {
          pattern: 'Heiban',
          desc: 'Todas las vocales deben durar exactamente 1 mora (un pulso uniforme de metrónomo). Evita acentuar con volumen.',
          example: 'あめ (ame)',
        },
        mnemonicTips: [
          { char: 'あ', story: 'Una antena de radio sobre una cruz; alguien grita ¡Aaa! al recibir señal.', visual: 'Antena / Cruz' },
          { char: 'い', story: 'Dos anguilas o dos "I" inclinadas una frente a otra.', visual: 'Anguilas' },
          { char: 'う', story: 'Un hombre inclinado cargando una bolsa pesada: ¡Uuu!.', visual: 'Bolsa pesada' },
          { char: 'え', story: 'Un gimnasta o ave exótica estirándose sobre una barra.', visual: 'Gimnasta' },
          { char: 'お', story: 'Un jugador de golf golpeando una bola con su palo.', visual: 'Golf' },
        ],
        tips: [
          'El Romaji es un andamiaje temporal: elimínalo cuanto antes.',
          'Cada vocal dura exactamente 1 mora (pulso temporal constante).',
        ],
      },
      {
        id: 'm1l2',
        t: 'か行',
        s: 'ka · ki · ku · ke · ko',
        xp: 40,
        chars: ['か', 'き', 'く', 'け', 'こ'],
        reads: ['ka', 'ki', 'ku', 'ke', 'ko'],
        note: 'Primera familia de consonantes. き (ki) aparece en kimochi (sentimiento) — la llave que abre emociones. こ en kokoro (corazón) y koko (aquí). Practica el orden hasta que sea automático.',
      },
      {
        id: 'm1l3',
        t: 'さ行',
        s: 'sa · shi · su · se · so',
        xp: 40,
        chars: ['さ', 'し', 'す', 'せ', 'そ'],
        reads: ['sa', 'shi', 'su', 'se', 'so'],
        note: "し es 'shi', no 'si'. Como en Shingeki no Kyojin. す en suki (好き, gustar). せ en sensei (先生). Error frecuente: confundir さ con き visualmente — observa los trazos.",
      },
      {
        id: 'm1l4',
        t: 'た行',
        s: 'ta · chi · tsu · te · to',
        xp: 40,
        chars: ['た', 'ち', 'つ', 'て', 'と'],
        reads: ['ta', 'chi', 'tsu', 'te', 'to'],
        note: "ち = 'chi' (no 'ti'). つ = 'tsu' — la ola del tsunami. Aparecen en tomodachi (友達, amigo) y tsuki (月, luna). Memoriza primero ち y つ — son los más irregulares de esta familia.",
      },
      {
        id: 'm1l5',
        t: 'な行',
        s: 'na · ni · nu · ne · no',
        xp: 40,
        chars: ['な', 'に', 'ぬ', 'ね', 'の'],
        reads: ['na', 'ni', 'nu', 'ne', 'no'],
        note: "の es la partícula de posesión más usada. 'Naruto no ramen' = el ramen de Naruto. Mnemotecnia: 'No nose. Whose nose?' para recordar que indica posesión. ね al final = '¿verdad?'",
      },
      {
        id: 'm1l6',
        t: 'は行',
        s: 'ha · hi · fu · he · ho',
        xp: 40,
        chars: ['は', 'ひ', 'ふ', 'へ', 'ほ'],
        reads: ['ha', 'hi', 'fu', 'he', 'ho'],
        note: "CRÍTICO: は como partícula de tema se pronuncia 'wa', no 'ha'. ふ = 'fu' (el monte Fuji). Este es el error más común de principiantes. ひ es la sonrisa amplia.",
      },
      {
        id: 'm1l7',
        t: 'ま行',
        s: 'ma · mi · mu · me · mo',
        xp: 40,
        chars: ['ま', 'み', 'む', 'め', 'も'],
        reads: ['ma', 'mi', 'mu', 'me', 'mo'],
        note: "ま = mamá con brazos abiertos. む = vaca mugiendo '¡Muu!' め = ojo (me = ojo en japonés). も = 'también'. 'Watashi mo' = yo también. み en mizu (水, agua).",
      },
      {
        id: 'm1l8',
        t: 'や行',
        s: 'ya · yu · yo',
        xp: 30,
        chars: ['や', 'ゆ', 'よ'],
        reads: ['ya', 'yu', 'yo'],
        note: "Solo 3 caracteres activos: el yak, el pez/submarino y el hombre que dice '¡Yo!'. Son la base de todos los diptongos — きゃ, しゃ, ちゃ se construyen con estos.",
      },
      {
        id: 'm1l9',
        t: 'ら行',
        s: 'ra · ri · ru · re · ro',
        xp: 40,
        chars: ['ら', 'り', 'る', 'れ', 'ろ'],
        reads: ['ra', 'ri', 'ru', 're', 'ro'],
        note: "El 'r' japonés no existe en español: mezcla r, l y d. La lengua toca brevemente el paladar. ら = conejo saltando. り = juncos del río. る al final de verbo = forma diccionario.",
      },
      {
        id: 'm1l10',
        t: 'わ行 · を · ん',
        s: 'wa · wo · n',
        xp: 30,
        chars: ['わ', 'を', 'ん'],
        reads: ['wa', 'wo', 'n'],
        note: "わ = avispero en la pared. を solo vive como partícula de objeto directo — '¡Woah, voy a tomar ese objeto!' ん = única consonante sola del japonés. Nunca inicia una palabra.",
      },
      {
        id: 'm1l11',
        t: 'Dakuon ゛ — か行 y さ行',
        s: 'ga · gi · gu · ge · go · za · ji · zu · ze · zo',
        xp: 50,
        chars: ['が', 'ぎ', 'ぐ', 'げ', 'ご', 'ざ', 'じ', 'ず', 'ぜ', 'ぞ'],
        reads: ['ga', 'gi', 'gu', 'ge', 'go', 'za', 'ji', 'zu', 'ze', 'zo'],
        note: 'El tenten (〃) suaviza/sonoriza: K→G, S→Z. じ (ji) es muy frecuente — jikan (時間, tiempo), jibun (自分, uno mismo). Genki (元気) usa が. El dakuon hace el sonido más grave y sonoro.',
      },
      {
        id: 'm1l12',
        t: 'Dakuon ゛ — た行 y は行',
        s: 'da · de · do · ba · bi · bu · be · bo',
        xp: 50,
        chars: ['だ', 'で', 'ど', 'ば', 'び', 'ぶ', 'べ', 'ぼ'],
        reads: ['da', 'de', 'do', 'ba', 'bi', 'bu', 'be', 'bo'],
        note: "T→D y H→B con tenten. ば = baka (ya la conoces del anime). で es partícula gramatical muy frecuente (lugar de acción: 'En Detroit comemos'). ど en doko (どこ, dónde).",
      },
      {
        id: 'm1l13',
        t: 'Handakuon ゜',
        s: 'pa · pi · pu · pe · po',
        xp: 30,
        chars: ['ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ'],
        reads: ['pa', 'pi', 'pu', 'pe', 'po'],
        note: "El maru (゜) es una pelota que hace '¡Pa!' Solo transforma は行 en P. Es el menos frecuente del hiragana puro. Panda en japonés = パンダ (katakana). En hiragana aparece en onomatopeyas.",
      },
      {
        id: 'm1l14',
        t: 'Youon ゃゅょ',
        s: 'kya · sha · cha · nya · hya · mya',
        xp: 50,
        chars: ['きゃ', 'しゃ', 'ちゃ', 'にゃ', 'ひゃ', 'みゃ'],
        reads: ['kya', 'sha', 'cha', 'nya', 'hya', 'mya'],
        note: 'Consonante + ya/yu/yo pequeño = un solo golpe de voz. しゃ en sharingan. ちゃ en ocha (té). にゃ = sonido del gato (nyan). Nyokki (ñoquis) = ニョッキ en katakana.',
      },
      {
        id: 'm1l14b',
        t: 'Prosodia: Mora y Pitch Accent',
        s: 'ritmo · vocales largas · pausas',
        xp: 30,
        chars: ['おばさん', 'おばあさん', 'きって', 'きて'],
        reads: ['obasan', 'obaasan', 'kitte', 'kite'],
        note: 'El japonés es isócrono por mora: cada unidad (incluida una vocal larga o una pausa) dura lo mismo. No uses acento de volumen como en español — usa Pitch Accent (tono): Atamadaka (cae al inicio), Nakadaka (sube y cae en medio), Odaka (sube y cae con la partícula) y Heiban (plano, se mantiene alto). Chouon (vocal larga): おばさん (tía) vs おばあさん (abuela) — la duración cambia el significado. Sokuon (っ, pausa geminada): きって (sello) vs きて (ven) — la pausa antes de la consonante también cambia el significado. Practica el ritmo constante, no el volumen.',
      },
      {
        id: 'm1l15',
        t: 'Sokuon っ y Chouon',
        s: 'pausa · doble consonante · alargamiento',
        xp: 40,
        chars: ['って', 'っか', 'っぱ', 'っさ'],
        reads: ['tte', 'kka', 'ppa', 'ssa'],
        note: 'っ crea pausa y duplica la consonante siguiente. Zasshi (revista) = ざっし. En hiragana el alargamiento usa la misma vocal: okaasan = おかあさん. En katakana usa el guion ー: keeki = ケーキ.',
      },
    ],
  },
  {
    id: 'm2',
    levelNum: 1,
    levelTitle: 'Nivel 1: Fundamentos Absolutos',
    block: 'I',
    bLabel: 'Alfabetización y Fonética',
    title: 'Módulo 2',
    sub: 'Katakana — Préstamos y Énfasis',
    color: '#98D96A',
    xpE: 200,
    req: 'm1',
    lessons: [
      {
        id: 'm2l1',
        t: 'ア行',
        s: 'a · i · u · e · o',
        xp: 40,
        chars: ['ア', 'イ', 'ウ', 'エ', 'オ'],
        reads: ['a', 'i', 'u', 'e', 'o'],
        note: 'Misma fonética que hiragana, trazos angulares y rectos. Katakana = extranjerismos, nombres y énfasis. Airon (plancha), Inku (tinta), Uinnaa (salchicha Viena), Epuron (delantal), Ootobai (moto).',
      },
      {
        id: 'm2l2',
        t: 'カ行',
        s: 'ka · ki · ku · ke · ko',
        xp: 40,
        chars: ['カ', 'キ', 'ク', 'ケ', 'コ'],
        reads: ['ka', 'ki', 'ku', 'ke', 'ko'],
        note: 'Kamera (cámara), Kiroguramu (kilogramo), Kureyon (crayón), Keeki (torta), Koohii (café). コーヒー = coffee — nota el guion largo ー que alarga la vocal. Caja abierta hacia la izquierda.',
      },
      {
        id: 'm2l3',
        t: 'サ行 — シ vs ツ',
        s: 'sa · shi · su · se · so',
        xp: 40,
        chars: ['サ', 'シ', 'ス', 'セ', 'ソ'],
        reads: ['sa', 'shi', 'su', 'se', 'so'],
        note: 'CLAVE: シ (shi) — los trazos miran HACIA ARRIBA, como alguien esquiando. Saboten (cactus), Shiisoo (subibaja), Surippa (pantuflas), Seroteepu (cinta), Sofa (sofá). Sakkaa = fútbol.',
      },
      {
        id: 'm2l4',
        t: 'タ行 — ツ vs シ',
        s: 'ta · chi · tsu · te · to',
        xp: 40,
        chars: ['タ', 'チ', 'ツ', 'テ', 'ト'],
        reads: ['ta', 'chi', 'tsu', 'te', 'to'],
        note: 'CLAVE: ツ (tsu) — los trazos miran HACIA ABAJO, aterrorizados por el tsunami. Taoru (toalla), Chiizu (queso), Tsuaa (tour), Tento (carpa), Toranpu (cartas). Terebi = TV.',
      },
      {
        id: 'm2l5',
        t: 'ナ行',
        s: 'na · ni · nu · ne · no',
        xp: 40,
        chars: ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ'],
        reads: ['na', 'ni', 'nu', 'ne', 'no'],
        note: 'Naifu (cuchillo), Nikoniko (sonrisa — dos líneas paralelas), Nu, Nekutai (corbata), Nooto (cuaderno — un trazo diagonal simple). ノ es la partícula の en katakana.',
      },
      {
        id: 'm2l6',
        t: 'ハ行',
        s: 'ha · hi · fu · he · ho',
        xp: 40,
        chars: ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ'],
        reads: ['ha', 'hi', 'fu', 'he', 'ho'],
        note: 'Hangaa (percha — forma de V), Hiitaa (estufa), Furaipan (sartén — gancho), Herumetto (casco — idéntico a へ hiragana), Hottokeeki (hotcake). Hoteru = hotel.',
      },
      {
        id: 'm2l7',
        t: 'マ行',
        s: 'ma · mi · mu · me · mo',
        xp: 40,
        chars: ['マ', 'ミ', 'ム', 'メ', 'モ'],
        reads: ['ma', 'mi', 'mu', 'me', 'mo'],
        note: 'Mafuraa (bufanda), Minikaa (auto pequeño — tres trazos diagonales), Muudo (ánimo/mood), Medaru (medalla — forma de X), Mootaabooto (barco motor). Manga = マンガ.',
      },
      {
        id: 'm2l8',
        t: 'ヤ行',
        s: 'ya · yu · yo',
        xp: 30,
        chars: ['ヤ', 'ユ', 'ヨ'],
        reads: ['ya', 'yu', 'yo'],
        note: 'Taiya (neumático), Yuufoo (OVNI), Yooyoo (yoyó — parece E invertida). Solo 3 caracteres como en hiragana. Yunifoomo = uniforme. Yooguruto = yogurt.',
      },
      {
        id: 'm2l9',
        t: 'ラ行',
        s: 'ra · ri · ru · re · ro',
        xp: 40,
        chars: ['ラ', 'リ', 'ル', 'レ', 'ロ'],
        reads: ['ra', 'ri', 'ru', 're', 'ro'],
        note: 'Raamen (ramen — nota ー para alargar), Ribon (listón/moño), Rubii (rubí), Reinkooto (impermeable), Rooraasukeeto (patines — cuadrado perfecto). Reberu = level.',
      },
      {
        id: 'm2l10',
        t: 'ワ行 · ヲ · ン — ン vs ソ',
        s: 'wa · wo · n',
        xp: 30,
        chars: ['ワ', 'ヲ', 'ン'],
        reads: ['wa', 'wo', 'n'],
        note: 'CLAVE: ン (n) tiene trazo largo HORIZONTAL. ソ (so) tiene trazo casi vertical. Nunca confundirlos. Waishatsu (camisa elegante), Wotagei (baile de fans), ン nunca inicia palabra. Wain = wine.',
      },
      {
        id: 'm2l11',
        t: 'Dakuon y Sonidos Especiales',
        s: 'ga · za · da · ba + fa · ti · va',
        xp: 50,
        chars: ['ガ', 'ザ', 'ダ', 'バ', 'ファ', 'ティ', 'ヴァ'],
        reads: ['ga', 'za', 'da', 'ba', 'fa', 'ti', 'va'],
        note: 'Misma lógica que hiragana con tenten. Sonidos especiales modernos: ティ (ti) en paatii (fiesta), ファ (fa) en sofa (ソファ), ウィ (wi), ヴァ (va). Solo katakana puede crear estos sonidos.',
      },
      {
        id: 'm2l12',
        t: 'Guion largo ー y Sokuon ッ',
        s: 'alargamiento · doble consonante',
        xp: 40,
        chars: ['コーヒー', 'スーパー', 'ベッド', 'ネット'],
        reads: ['koohii', 'suupaa', 'beddo', 'netto'],
        note: 'ー alarga la vocal anterior — exclusivo de katakana. ッ duplica consonante: beddo (cama), netto (internet). Detectar estos patrones es clave para leer préstamos del inglés en japonés.',
      },
    ],
  },
  {
    id: 'm3',
    levelNum: 2,
    levelTitle: 'Nivel 2: Gramática Elemental I',
    block: 'II',
    bLabel: 'Gramática Fundacional',
    title: 'Módulo 3',
    sub: 'Identidad · DESU · KOSOADO',
    color: '#7C3AED',
    xpE: 250,
    req: 'm2',
    lessons: [
      {
        id: 'm3l1',
        t: 'Oraciones Nominales',
        s: 'desu · wa · ka · mo',
        xp: 60,
        chars: ['は', 'が', 'を', 'に', 'で', 'も', 'か'],
        reads: ['wa', 'ga', 'wo', 'ni', 'de', 'mo', 'ka'],
        vocab: [
          { jp: 'わたし は ジョージ です', es: 'Yo soy George' },
          { jp: 'エクアドル じん です', es: 'Soy ecuatoriano' },
          { jp: 'どうぞ よろしく', es: 'Mucho gusto' },
        ],
        note: "DESU no es solo 'ser' — es un indicador de registro formal que dice al oyente: 'te hablo con respeto'. La partícula KA al final convierte cualquier oración en pregunta sin cambiar el tono. Estructura: [Sujeto] WA [predicado] DESU. Error común: confundir WA con GA. WA presenta información ya conocida (el tema del que hablamos); GA marca al sujeto cuando la información es nueva o específica ('¿Quién hizo esto?' → responde con GA).",
      },
      {
        id: 'm3l1b',
        t: 'Jikoshoukai y Honoríficos',
        s: 'presentación personal · -san · -kun · -sama',
        xp: 50,
        chars: ['さん', 'くん', 'さま'],
        reads: ['san', 'kun', 'sama'],
        vocab: [
          { jp: 'はじめまして', es: 'Mucho gusto (al conocer a alguien)' },
          { jp: 'わたし は [なまえ] です', es: 'Yo soy [nombre]' },
          { jp: 'よろしく おねがいします', es: 'Encantado / espero su buena disposición' },
        ],
        note: 'Protocolo de Jikoshoukai (自己紹介, presentación personal): Hajimemashite → Watashi wa [Nombre] desu → Yoroshiku onegaishimasu. Honoríficos: -san (respeto general, para cualquier persona), -kun (informal, para jóvenes u hombres cercanos), -sama (máxima cortesía, clientes o cartas formales). Regla de oro: NUNCA uses un honorífico con tu propio nombre — sería como auto-alabarte.',
      },
      {
        id: 'm3l2',
        t: 'Partículas WA y MO',
        s: 'tema · también · nacionalidad',
        xp: 60,
        chars: ['は', 'も', 'じん'],
        reads: ['wa', 'mo', 'jin'],
        vocab: [
          {
            jp: 'たなかさん も にほんじん です',
            es: 'Tanaka también es japonés',
          },
          { jp: 'わたし も がくせい です', es: 'Yo también soy estudiante' },
        ],
        note: "WA pone un foco de luz sobre el tema ('En cuanto a...'). MO sustituye a WA para indicar inclusión ('también'). Nacionalidad: país + jin (人). Amerikajin, Doitsujin, Aruzenchinjin.",
      },
      {
        id: 'm3l3',
        t: 'Partícula NO y Profesiones',
        s: 'posesión · calificación',
        xp: 50,
        chars: ['の', 'せんせい', 'がくせい', 'かいしゃいん', 'いしゃ'],
        reads: ['no', 'sensei', 'gakusei', 'kaishain', 'isha'],
        vocab: [
          { jp: 'わたし の ほん', es: 'Mi libro (libro de mi propiedad)' },
          { jp: 'にほんご の せんせい', es: 'Profesor de japonés' },
          { jp: 'ナルト の せんせい は かかし です', es: 'El profesor de Naruto es Kakashi' },
          { jp: 'わたし は いしゃ です', es: 'Yo soy médico' },
        ],
        note: "NO conecta dos sustantivos: el primero posee al segundo. Mnemotecnia: 'No nose. Whose nose?' Profesiones: Sensei (profesor), Gakusei (estudiante), Kaishain (empleado), Isha (médico), Mangaka (dibujante).",
      },
      {
        id: 'm3l4',
        t: 'KOSOADO — Objetos',
        s: 'kore · sore · are · kono · sono · ano',
        xp: 60,
        chars: ['これ', 'それ', 'あれ', 'どれ', 'この', 'その', 'あの', 'どの'],
        reads: ['kore', 'sore', 'are', 'dore', 'kono', 'sono', 'ano', 'dono'],
        vocab: [
          { jp: 'これ は ポケモン の カード です', es: 'Esto es una carta de Pokémon' },
          { jp: 'あれ は マリオ です', es: 'Eso de allá es Mario' },
        ],
        note: 'KO=cerca mío, SO=cerca de ti, A=lejos de ambos, DO=pregunta. REGLA: Kore/Sore/Are REEMPLAZAN al sustantivo. Kono/Sono/Ano ACOMPAÑAN al sustantivo (Ej: Kono kagi = esta llave). Nunca solos.',
      },
      {
        id: 'm3l5',
        t: 'KOSOADO — Lugares',
        s: 'koko · soko · asoko · doko',
        xp: 50,
        chars: [
          'ここ',
          'そこ',
          'あそこ',
          'どこ',
          'こちら',
          'そちら',
          'あちら',
          'どちら',
        ],
        reads: [
          'koko',
          'soko',
          'asoko',
          'doko',
          'kochira',
          'sochira',
          'achira',
          'dochira',
        ],
        vocab: [
          { jp: 'トイレ は どこ です か', es: '¿Dónde está el baño?' },
          { jp: 'ここ は ハイラル です', es: 'Aquí es Hyrule' },
        ],
        note: "Misma lógica KO-SO-A-DO para lugares. こちら/そちら son versiones formales. La frase más útil en Japón: 'トイレはどこですか' (¿Dónde está el baño?). Si la llave está cerca de tu amigo: sore/sono.",
      },
    ],
  },
  {
    id: 'm4',
    levelNum: 2,
    levelTitle: 'Nivel 2: Gramática Elemental I',
    block: 'II',
    bLabel: 'Gramática Fundacional',
    title: 'Módulo 4',
    sub: 'Números · Tiempo · Calendario',
    color: '#12A8C2',
    xpE: 250,
    req: 'm3',
    lessons: [
      {
        id: 'm4l1',
        t: 'Números 0–10.000 + Goroawase',
        s: 'sistema numérico con anclajes anime',
        xp: 60,
        chars: [
          'いち',
          'に',
          'さん',
          'よん',
          'ご',
          'ろく',
          'なな',
          'はち',
          'きゅう',
          'じゅう',
        ],
        reads: [
          'ichi',
          'ni',
          'san',
          'yon',
          'go',
          'roku',
          'nana',
          'hachi',
          'kyuu',
          'juu',
        ],
        vocab: [
          { jp: 'わたし の でんわばんごう は いち に さん です', es: 'Mi número de teléfono es 1-2-3' },
          { jp: 'ドラゴンボール は なな こ あります', es: 'Hay 7 esferas del dragón' },
        ],
        note: 'Anclajes: Ichi = Ichigo Kurosaki. Ni = ni-san (hermano). San = Sanji (One Piece). Shi/Yon = muerte/4. Go = Son Goku. Juu = Jujutsu Kaisen. Japonés agrupa en 10.000 (man) no en 1.000. Irregulares: 300=sanbyaku, 600=roppyaku, 800=happyaku.',
      },
      {
        id: 'm4l2',
        t: 'Horas y Minutos',
        s: 'ji · fun · pun · excepciones',
        xp: 60,
        chars: [
          'じ',
          'ふん',
          'ぷん',
          'はん',
          'ごぜん',
          'ごご',
          'いま',
          'なんじ',
        ],
        reads: ['ji', 'fun', 'pun', 'han', 'gozen', 'gogo', 'ima', 'nanji'],
        vocab: [
          { jp: 'いま なんじ です か', es: '¿Qué hora es ahora?' },
          { jp: 'ごご さん じ です', es: 'Son las 3 de la tarde' },
        ],
        note: "Horas: número + ji. Excepciones críticas: 4=yoji, 7=shichiji, 9=kuji. Minutos -fun/-pun (irregular): 1,3,4,6,8,10 usan -pun (ippun, sanpun). はん = media hora. '今何時ですか' = ¿Qué hora es?",
      },
      {
        id: 'm4l3',
        t: 'Días de la Semana',
        s: 'elementos naturales + jutsus',
        xp: 50,
        chars: [
          'げつようび',
          'かようび',
          'すいようび',
          'もくようび',
          'きんようび',
          'どようび',
          'にちようび',
        ],
        reads: [
          'getsuyoubi',
          'kayoubi',
          'suiyoubi',
          'mokuyoubi',
          'kinyoubi',
          'doyoubi',
          'nichiyoubi',
        ],
        vocab: [
          { jp: 'きょう は もくようび です', es: 'Hoy es jueves' },
          { jp: 'すいようび は きさめ の ひ です', es: 'El miércoles es el día de Kisame' },
        ],
        note: 'Lunes=Luna(Getsuga Tenshou). Martes=Fuego(Katon). Miércoles=Agua(Suiton de Kisame). Jueves=Madera(Mokuton de Yamato). Viernes=Oro(Fullmetal). Sábado=Tierra(Doton). Domingo=Sol.',
      },
      {
        id: 'm4l4',
        t: 'Días del Mes + Partículas',
        s: 'fechas irregulares · ni · kara · made',
        xp: 60,
        chars: ['に', 'から', 'まで', 'いつ', 'なんにち'],
        reads: ['ni', 'kara', 'made', 'itsu', 'nannichi'],
        vocab: [
          { jp: 'いつ です か', es: '¿Cuándo es?' },
          { jp: 'げつようび から きんようび まで です', es: 'Es de lunes a viernes' },
        ],
        note: "Días irregulares: Día 1=Tsuitachi (Itachi+agua), Día 3=Mikka (Mickey 3 dedos), Día 5=Itsuka ('It's a car'), Día 20=Hatsuka (Hatsune Miku). NI=punto exacto de tiempo. KARA=desde. MADE=hasta.",
      },
    ],
  },
  {
    id: 'm5',
    levelNum: 3,
    levelTitle: 'Nivel 3: Gramática Elemental II',
    block: 'III',
    bLabel: 'Dinámica Verbal',
    title: 'Módulo 5',
    sub: 'Verbos · Conjugación · Partículas',
    color: '#10B981',
    xpE: 300,
    req: 'm4',
    lessons: [
      {
        id: 'm5l1',
        t: 'Los 3 Grupos de Verbos',
        s: 'u-verbs · ru-verbs · suru · kuru',
        xp: 70,
        chars: ['かく', 'のむ', 'みる', 'たべる', 'する', 'くる'],
        reads: ['kaku', 'nomu', 'miru', 'taberu', 'suru', 'kuru'],
        vocab: [
          { jp: 'まんが を かく', es: 'Dibujo un manga' },
          { jp: 'ラーメン を たべる', es: 'Como ramen' },
        ],
        note: 'Grupo 1 (U): consonante+u, cambia vocal → +masu (kaku→kakimasu). Grupo 2 (Ru): termina en ru precedido de e/i, elimina ru → +masu (taberu→tabemasu). Grupo 3: solo suru y kuru — memorización directa.',
      },
      {
        id: 'm5l2',
        t: 'Forma Masu — 4 conjugaciones',
        s: 'presente · negación · pasado · deseo',
        xp: 70,
        chars: [
          'ます',
          'ません',
          'ました',
          'ませんでした',
          'たいです',
          'たくないです',
        ],
        reads: [
          'masu',
          'masen',
          'mashita',
          'masen deshita',
          'tai desu',
          'takunai desu',
        ],
        vocab: [
          { jp: 'アニメ を みます', es: 'Veo anime' },
          { jp: 'ゲーム を したいです', es: 'Quiero jugar videojuegos' },
        ],
        note: 'Masu=presente/futuro. Masen=negación. Mashita=pasado afirmativo. Masen deshita=pasado negativo. たいです=quiero hacer X. Lengua aglutinante: la raíz nunca cambia, solo los sufijos.',
      },
      {
        id: 'm5l3',
        t: 'Partículas de Acción',
        s: 'wo · de · to · kara · made · e',
        xp: 60,
        chars: ['を', 'で', 'と', 'から', 'まで', 'や', 'か', 'へ'],
        reads: ['wo', 'de', 'to', 'kara', 'made', 'ya', 'ka', 'e'],
        vocab: [
          { jp: 'がっこう へ いきます', es: 'Voy hacia la escuela' },
          { jp: 'ともだち と ゲーム を します', es: 'Juego videojuegos con mi amigo' },
        ],
        note: "WO (を): objeto directo. 'Woah, voy a tomar ese objeto'. DE (で): lugar de acción. 'En Detroit comemos dátiles'. TO (と): compañía ('con') o enumeración ('y'). KARA=desde, MADE=hasta. HE (へ, se lee 'e' como partícula): dirección del movimiento — 'gakkou e ikimasu' (voy hacia la escuela).",
      },
      {
        id: 'm5l4',
        t: 'Verbos de Existencia',
        s: 'aru · iru',
        xp: 60,
        chars: ['ある', 'いる', 'つくえ', 'ねこ'],
        reads: ['aru', 'iru', 'tsukue', 'neko'],
        vocab: [
          { jp: 'つくえ が あります', es: 'Hay un escritorio (objeto inanimado)' },
          { jp: 'ねこ が います', es: 'Hay un gato (ser vivo)' },
        ],
        note: 'ARU (ある): existencia de objetos inanimados — libros, mesas, edificios. IRU (いる): existencia de seres vivos — personas, animales. A diferencia del español (donde "hay" sirve para todo), el japonés obliga a elegir según si el sujeto está vivo o no. Mnemotecnia: "iru" suena a "vivir".',
      },
    ],
  },
  {
    id: 'm6',
    levelNum: 4,
    levelTitle: 'Nivel 4: Adquisición Sinográfica',
    block: 'IV',
    bLabel: 'Kanji Inicial',
    title: 'Módulo 6',
    sub: 'Ideogramas · Radicales · Colores',
    color: '#F59E0B',
    xpE: 350,
    req: 'm5',
    lessons: [
      {
        id: 'm6l1',
        t: 'Anatomía del Kanji',
        s: 'onyomi · kunyomi · radicales',
        xp: 80,
        chars: ['日', '月', '火', '水', '木', '金', '土', '山', '川', '人'],
        reads: [
          'nichi',
          'getsu',
          'ka',
          'sui',
          'moku',
          'kin',
          'do',
          'yama',
          'kawa',
          'hito',
        ],
        note: 'Radicales = piezas de LEGO conceptuales. 人 (persona) aparece en 何 (qué) y 会 (reunirse). Onyomi=lectura china, usada en compuestos (Gakusei). Kunyomi=japonesa, usada solo (Hito = persona sola).',
      },
      {
        id: 'm6l2',
        t: 'Kanji de los Elementos',
        s: 'días + naturaleza + Naruto',
        xp: 80,
        chars: ['木', '金', '土', '山', '川', '人', '大', '小', '中', '日'],
        reads: [
          'moku',
          'kin',
          'do',
          'yama',
          'kawa',
          'hito',
          'dai',
          'shou',
          'chuu',
          'nichi',
        ],
        note: '木=árbol (Mokuton). El radical de árbol en 森 (bosque=tres árboles) y 林 (arboleda=dos). 大 parece una persona con brazos extendidos = grande. 中 = dentro/centro. Aprende significado visual primero.',
      },
      {
        id: 'm6l3',
        t: 'Colores con Mnemotecnia Anime',
        s: 'shiro · kuro · midori · aka · ao',
        xp: 80,
        chars: [
          'しろ',
          'くろ',
          'みどり',
          'あか',
          'あお',
          'きいろ',
          'ちゃいろ',
          'むらさき',
        ],
        reads: [
          'shiro',
          'kuro',
          'midori',
          'aka',
          'ao',
          'kiiro',
          'chairo',
          'murasaki',
        ],
        note: 'Shiro=blanco (Shirohige=Barba Blanca). Kuro=negro (Kurohige=Barba Negra). Midori=verde (Izuku Midoriya=Deku). Aka=rojo (Akatsuki). Ao=azul (Opening Blue Bird). Kiiro=amarillo (llave dorada).',
      },
      {
        id: 'm6l4',
        t: 'Kanji Fundamentales N5',
        s: 'números · posición · familia',
        xp: 100,
        chars: ['一', '二', '三', '大', '小', '上', '下', '日', '月', '人'],
        reads: [
          'ichi',
          'ni',
          'san',
          'dai',
          'shou',
          'jou',
          'ka',
          'nichi',
          'getsu',
          'hito',
        ],
        note: 'JLPT N5 requiere ~100 kanji. Números, direcciones y familia son el núcleo. 大 (grande) = persona con brazos extendidos. 上 (arriba) / 下 (abajo). Aprende el significado visual antes que las lecturas.',
      },
    ],
  },
  {
    id: 'm7',
    levelNum: 5,
    levelTitle: 'Nivel 5: Gramática Intermedia I',
    block: 'V',
    bLabel: 'Complejidad Intermedia',
    title: 'Módulo 7',
    sub: 'Relaciones y Modos Gramaticales',
    color: '#B14AE2',
    xpE: 400,
    req: 'm6',
    lessons: [
      {
        id: 'm7l1',
        t: 'Adjetivos y Estados de Ánimo',
        s: 'i-adjetivos · na-adjetivos · suki · kirai',
        xp: 90,
        chars: ['たかい', 'やすい', 'おおきい', 'きれい', 'げんき', 'すき', 'きらい'],
        reads: ['takai', 'yasui', 'ookii', 'kirei', 'genki', 'suki', 'kirai'],
        vocab: [
          { jp: 'この まんが は やすい です', es: 'Este manga es barato' },
          { jp: 'せんせい は げんき です', es: 'El profesor está lleno de energía' },
        ],
        note: 'Adjetivos Tipo I (terminan en I): takai (caro/alto), yasui (barato), ookii (grande). Negación con el Método del Kunai: se corta la I final y se añade KUNAI (Takai → Takakunai). Adjetivos Tipo NA: requieren NA antes del sustantivo (kirei na hito = persona bonita; genki na inu = perro con energía). Gustos: SUKI (gustar) y KIRAI (disgustar) se construyen como adjetivos NA, no como verbos — el objeto de gusto se marca con GA, no con WO.',
      },
      {
        id: 'm7l2',
        t: 'Transitividad y Voz',
        s: 'jidoushi · tadoushi · ga · wo',
        xp: 90,
        chars: ['あく', 'あける', 'しまる', 'しめる'],
        reads: ['aku', 'akeru', 'shimaru', 'shimeru'],
        vocab: [
          { jp: 'まど が あく', es: 'La ventana se abre (sola, sin agente)' },
          { jp: 'まど を あける', es: 'Abro la ventana (yo actúo sobre ella)' },
        ],
        note: 'A diferencia del español, el japonés tiene pares de verbos distintos para acciones automáticas (Jidoushi, intransitivo — algo pasa sin agente explícito, se marca con GA) y acciones sobre un objeto (Tadoushi, transitivo — alguien actúa sobre algo, se marca con WO). Mado ga aku (la ventana se abre) vs Mado wo akeru (abro la ventana). Reconocer estos pares es clave para sonar natural: los principiantes suelen forzar el verbo transitivo donde un nativo usaría el intransitivo.',
      },
      {
        id: 'm7l3',
        t: 'Perspectiva y Empatía Gramatical',
        s: 'pasivas · causativo · procesabilidad',
        xp: 100,
        chars: ['かく', 'かかれる', 'たべる', 'たべられる'],
        reads: ['kaku', 'kakareru', 'taberu', 'taberareru'],
        vocab: [
          { jp: 'この ゲーム は みんな に あいされる', es: 'Este juego es amado por todos' },
          { jp: 'ラーメン が たべられる', es: 'El ramen puede comerse' },
        ],
        note: 'El japonés prefiere construcciones pasivas naturales que reflejan empatía o perspectiva del hablante — incluso para expresar una molestia ("ame ni furareta" = me afectó que lloviera, literalmente "fui llovido"). Formación: raíz + ARERU/RARERU (kaku→kakareru, taberu→taberareru). Teoría de la Procesabilidad: las estructuras pasivas y causativas son de las más difíciles de adquirir porque exigen más carga en la memoria de trabajo — se aprenden mejor después de dominar la voz activa con soltura.',
      },
    ],
  },
  {
    id: 'm8',
    levelNum: 6,
    levelTitle: 'Nivel 6: Lectura e Inmersión',
    block: 'VI',
    bLabel: 'Fluidez Avanzada',
    title: 'Módulo 8',
    sub: 'Competencia Real y Preparación JLPT',
    color: '#E24A7A',
    xpE: 450,
    req: 'm7',
    lessons: [
      {
        id: 'm8l1',
        t: 'Shadowing Avanzado',
        s: 'habla natural · reducciones · prosodia',
        xp: 80,
        chars: ['たべてる', 'たべている', 'わかんない', 'わからない'],
        reads: ['tabeteru', 'tabeteiru', 'wakannai', 'wakaranai'],
        vocab: [
          { jp: 'なに を たべてる の', es: '¿Qué estás comiendo?' },
          { jp: 'ぜんぜん わかんない', es: 'No entiendo nada' },
        ],
        note: 'Prosodic Shadowing: repetir audio nativo con milisegundos de desfase, enfocándote en el ritmo real y las reducciones de partículas del habla rápida, sin apoyo visual. El japonés hablado casual contrae formas largas: tabeteiru → tabeteru, wakaranai → wakannai. Un aprendiz que solo estudia la forma "de libro" no entenderá conversaciones reales. Practica shadowing con anime o dramas sin subtítulos una vez que domines la gramática base.',
      },
      {
        id: 'm8l2',
        t: 'Lectura Crítica y Tadoku',
        s: 'conectores lógicos · lectura extensiva',
        xp: 80,
        chars: ['つまり', 'しかし', 'なぜなら', 'たとえば'],
        reads: ['tsumari', 'shikashi', 'nazenara', 'tatoeba'],
        vocab: [
          { jp: 'つまり かれ は ヒーロー です', es: 'En resumen, él es un héroe' },
          { jp: 'しかし それ は ちがいます', es: 'Sin embargo, eso es diferente' },
        ],
        note: 'Transición de libros graduados (Genki) a materiales auténticos (Tobira, Shin Kanzen Master). Tadoku: lectura extensiva por placer, sin traducir palabra por palabra, para automatizar vocabulario y estructuras. Los conectores lógicos son anclas para seguir el argumento de un texto: TSUMARI (en resumen), SHIKASHI (sin embargo), NAZENARA (porque), TATOEBA (por ejemplo). Identificarlos rápido es la diferencia entre leer y solo traducir.',
      },
      {
        id: 'm8l3',
        t: 'Pragmática Social y Keigo',
        s: 'sonkeigo · kenjougo · cortesía profesional',
        xp: 90,
        chars: ['いらっしゃる', 'まいる', 'めしあがる', 'いただく'],
        reads: ['irassharu', 'mairu', 'meshiagaru', 'itadaku'],
        vocab: [
          { jp: 'せんせい は いらっしゃいます', es: 'El profesor viene/está (sonkeigo, eleva al otro)' },
          { jp: 'わたし が まいります', es: 'Yo iré (kenjougo, me humilla a mí mismo)' },
        ],
        note: 'El lenguaje honorífico (Keigo) es obligatorio en entornos profesionales japoneses. Sonkeigo: eleva al oyente o a un tercero de respeto (iru/iku/kuru → irassharu; taberu → meshiagaru). Kenjougo: humilla al hablante para mostrar respeto (iku/kuru → mairu; taberu/morau → itadaku). Nunca se usa Sonkeigo para uno mismo ni Kenjougo para el interlocutor — invertirlos es un error grave de cortesía.',
      },
      {
        id: 'm8l4',
        t: 'Preparación JLPT N2–N1',
        s: 'conectores avanzados · comprensión lectora',
        xp: 100,
        chars: ['それゆえ', 'にもかかわらず', 'いっぽう', 'したがって'],
        reads: ['soreyue', 'nimokakawarazu', 'ippou', 'shitagatte'],
        vocab: [
          { jp: 'それゆえ わたし は べんきょう します', es: 'Por lo tanto, yo estudio' },
          { jp: 'いっぽう かれ は やすみます', es: 'Por otro lado, él descansa' },
        ],
        note: 'La lógica subyacente del JLPT N2-N1 es identificar la tesis del autor y evitar distractores en textos académicos, no traducir cada palabra. El "Principio del Primer Sustantivo" ayuda a interpretar oraciones pasivas complejas: el primer sustantivo suele ser el tema, no necesariamente el agente. Conectores avanzados frecuentes en textos N2-N1: SOREYUE (por lo tanto), NIMOKAKAWARAZU (a pesar de), IPPOU (por otro lado), SHITAGATTE (en consecuencia).',
      },
    ],
  },
];
