import type { Module } from '../types';

// Contenido: módulos, lecciones, caracteres y notas didácticas.
export const MODULES: Module[] = [
  {
    id: 'm1',
    levelNum: 1,
    levelTitle: 'Nivel 1: Fundamentos Absolutos',
    block: 'I',
    bLabel: 'Alfabetización y Fonética',
    title: 'Módulo 1',
    sub: 'Hiragana — El Código Nativo',
    color: '#8CF244',
    xpE: 200,
    lessons: [
      {
        id: 'm1l1',
        t: 'あ行',
        s: 'a · i · u · e · o',
        xp: 40,
        chars: ['あ', 'い', 'う', 'え', 'お'],
        reads: ['a', 'i', 'u', 'e', 'o'],
        note: 'Las 5 vocales puras. El japonés NO tiene diptongos — cada vocal es un sonido limpio e independiente. Elimina el romaji cuanto antes para no crear vicios de pronunciación.',
        objective: 'Dominar la pronunciación limpia de las 5 vocales puras y sus mnemotecnias iconográficas.',
        tables: [
          {
            title: 'Fila de las Vocales Puras (あ行)',
            headers: ['Kana', 'Romaji', 'Pronunciación', 'Mnemotecnia Visual', 'Ejemplo'],
            rows: [
              ['あ', 'a', 'Como "a" del español', 'Antena de radio con lazo cruzado', 'あめ (Lluvia/Dulce)'],
              ['い', 'i', 'Como "i" del español', 'Dos anguilas o dos "I" paralelas', 'いい (Bueno)'],
              ['う', 'u', 'Como "u" (labios relajados)', 'Persona cargando bolsa en espalda', 'うた (Canción)'],
              ['え', 'e', 'Como "e" del español', 'Gimnasta estirándose sobre barra', 'えん (Yen)'],
              ['お', 'o', 'Como "o" del español', 'Golfista haciendo tiro de salida', 'おいしい (Delicioso)'],
            ],
          },
        ],
        pitchNote: {
          pattern: 'Heiban',
          desc: 'Todas las vocales deben durar exactamente 1 mora (un pulso uniforme de metrónomo). Evita acentuar con volumen.',
          example: 'あめ (ame)',
        },
        mnemonicTips: [
          { char: 'あ', story: 'Una antena de radio sobre una cruz; alguien grita ¡Aaa! al recibir señal.', visual: 'Antena / Cruz' },
          { char: 'い', story: 'Dos anguilas o dos "I" inclinadas una frente a otra.', visual: 'Anguilas' },
          { char: 'う', story: 'Un hombre inclinado cargando una bolsa pesada: ¡Uuu!.', visual: 'Bolsa pesada' },
          { char: 'え', story: 'Un gimnasta o ave exótica estirándose sobre una barra.', visual: 'Gimnasta' },
          { char: 'お', story: 'Un jugador de golf golpeando una bola con su palo.', visual: 'Golf' },
        ],
        tips: [
          'El Romaji es un andamiaje temporal: elimínalo cuanto antes.',
          'Cada vocal dura exactamente 1 mora (pulso temporal constante).',
        ],
      },
      {
        id: 'm1l2',
        t: 'か行',
        s: 'ka · ki · ku · ke · ko',
        xp: 40,
        chars: ['か', 'き', 'く', 'け', 'こ'],
        reads: ['ka', 'ki', 'ku', 'ke', 'ko'],
        note: 'Primera familia de consonantes. き (ki) aparece en kimochi (sentimiento) — la llave que abre emociones. こ en kokoro (corazón) y koko (aquí). Practica el orden hasta que sea automático.',
      },
      {
        id: 'm1l3',
        t: 'さ行',
        s: 'sa · shi · su · se · so',
        xp: 40,
        chars: ['さ', 'し', 'す', 'せ', 'そ'],
        reads: ['sa', 'shi', 'su', 'se', 'so'],
        note: "し es 'shi', no 'si'. Como en Shingeki no Kyojin. す en suki (好き, gustar). せ en sensei (先生). Error frecuente: confundir さ con き visualmente — observa los trazos.",
      },
      {
        id: 'm1l4',
        t: 'た行',
        s: 'ta · chi · tsu · te · to',
        xp: 40,
        chars: ['た', 'ち', 'つ', 'て', 'と'],
        reads: ['ta', 'chi', 'tsu', 'te', 'to'],
        note: "ち = 'chi' (no 'ti'). つ = 'tsu' — la ola del tsunami. Aparecen en tomodachi (友達, amigo) y tsuki (月, luna). Memoriza primero ち y つ — son los más irregulares de esta familia.",
      },
      {
        id: 'm1l5',
        t: 'な行',
        s: 'na · ni · nu · ne · no',
        xp: 40,
        chars: ['な', 'に', 'ぬ', 'ね', 'の'],
        reads: ['na', 'ni', 'nu', 'ne', 'no'],
        note: "の es la partícula de posesión más usada. 'Naruto no ramen' = el ramen de Naruto. Mnemotecnia: 'No nose. Whose nose?' para recordar que indica posesión. ね al final = '¿verdad?'",
      },
      {
        id: 'm1l6',
        t: 'は行',
        s: 'ha · hi · fu · he · ho',
        xp: 40,
        chars: ['は', 'ひ', 'ふ', 'へ', 'ほ'],
        reads: ['ha', 'hi', 'fu', 'he', 'ho'],
        note: "CRÍTICO: は como partícula de tema se pronuncia 'wa', no 'ha'. ふ = 'fu' (el monte Fuji). Este es el error más común de principiantes. ひ es la sonrisa amplia.",
      },
      {
        id: 'm1l7',
        t: 'ま行',
        s: 'ma · mi · mu · me · mo',
        xp: 40,
        chars: ['ま', 'み', 'む', 'め', 'も'],
        reads: ['ma', 'mi', 'mu', 'me', 'mo'],
        note: "ま = mamá con brazos abiertos. む = vaca mugiendo '¡Muu!' め = ojo (me = ojo en japonés). も = 'también'. 'Watashi mo' = yo también. み en mizu (水, agua).",
      },
      {
        id: 'm1l8',
        t: 'や行',
        s: 'ya · yu · yo',
        xp: 30,
        chars: ['や', 'ゆ', 'よ'],
        reads: ['ya', 'yu', 'yo'],
        note: "Solo 3 caracteres activos: el yak, el pez/submarino y el hombre que dice '¡Yo!'. Son la base de todos los diptongos — きゃ, しゃ, ちゃ se construyen con estos.",
      },
      {
        id: 'm1l9',
        t: 'ら行',
        s: 'ra · ri · ru · re · ro',
        xp: 40,
        chars: ['ら', 'り', 'る', 'れ', 'ろ'],
        reads: ['ra', 'ri', 'ru', 're', 'ro'],
        note: "El 'r' japonés no existe en español: mezcla r, l y d. La lengua toca brevemente el paladar. ら = conejo saltando. り = juncos del río. る al final de verbo = forma diccionario.",
      },
      {
        id: 'm1l10',
        t: 'わ行 · を · ん',
        s: 'wa · wo · n',
        xp: 30,
        chars: ['わ', 'を', 'ん'],
        reads: ['wa', 'wo', 'n'],
        note: "わ = avispero en la pared. を solo vive como partícula de objeto directo — '¡Woah, voy a tomar ese objeto!' ん = única consonante sola del japonés. Nunca inicia una palabra.",
      },
      {
        id: 'm1l11',
        t: 'Dakuon ゛ — か行 y さ行',
        s: 'ga · gi · gu · ge · go · za · ji · zu · ze · zo',
        xp: 50,
        chars: ['が', 'ぎ', 'ぐ', 'げ', 'ご', 'ざ', 'じ', 'ず', 'ぜ', 'ぞ'],
        reads: ['ga', 'gi', 'gu', 'ge', 'go', 'za', 'ji', 'zu', 'ze', 'zo'],
        note: 'El tenten (〃) suaviza/sonoriza: K→G, S→Z. じ (ji) es muy frecuente — jikan (時間, tiempo), jibun (自分, uno mismo). Genki (元気) usa が. El dakuon hace el sonido más grave y sonoro.',
      },
      {
        id: 'm1l12',
        t: 'Dakuon ゛ — た行 y は行',
        s: 'da · de · do · ba · bi · bu · be · bo',
        xp: 50,
        chars: ['だ', 'で', 'ど', 'ば', 'び', 'ぶ', 'べ', 'ぼ'],
        reads: ['da', 'de', 'do', 'ba', 'bi', 'bu', 'be', 'bo'],
        note: "T→D y H→B con tenten. ば = baka (ya la conoces del anime). で es partícula gramatical muy frecuente (lugar de acción: 'En Detroit comemos'). ど en doko (どこ, dónde).",
      },
      {
        id: 'm1l13',
        t: 'Handakuon ゜',
        s: 'pa · pi · pu · pe · po',
        xp: 30,
        chars: ['ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ'],
        reads: ['pa', 'pi', 'pu', 'pe', 'po'],
        note: "El maru (゜) es una pelota que hace '¡Pa!' Solo transforma は行 en P. Es el menos frecuente del hiragana puro. Panda en japonés = パンダ (katakana). En hiragana aparece en onomatopeyas.",
      },
      {
        id: 'm1l14',
        t: 'Youon ゃゅょ',
        s: 'kya · sha · cha · nya · hya · mya',
        xp: 50,
        chars: ['きゃ', 'しゃ', 'ちゃ', 'にゃ', 'ひゃ', 'みゃ'],
        reads: ['kya', 'sha', 'cha', 'nya', 'hya', 'mya'],
        note: 'Consonante + ya/yu/yo pequeño = un solo golpe de voz. しゃ en sharingan. ちゃ en ocha (té). にゃ = sonido del gato (nyan). Nyokki (ñoquis) = ニョッキ en katakana.',
      },
      {
        id: 'm1l14b',
        t: 'Prosodia: Mora y Pitch Accent',
        s: 'ritmo · vocales largas · pausas',
        xp: 30,
        chars: ['おばさん', 'おばあさん', 'きって', 'きて'],
        reads: ['obasan', 'obaasan', 'kitte', 'kite'],
        note: 'El japonés es isócrono por mora: cada unidad (incluida una vocal larga o una pausa) dura lo mismo. No uses acento de volumen como en español — usa Pitch Accent (tono): Atamadaka (cae al inicio), Nakadaka (sube y cae en medio), Odaka (sube y cae con la partícula) y Heiban (plano, se mantiene alto). Chouon (vocal larga): おばさん (tía) vs おばあさん (abuela) — la duración cambia el significado. Sokuon (っ, pausa geminada): きって (sello) vs きて (ven) — la pausa antes de la consonante también cambia el significado. Practica el ritmo constante, no el volumen.',
      },
      {
        id: 'm1l15',
        t: 'Sokuon っ y Chouon',
        s: 'pausa · doble consonante · alargamiento',
        xp: 40,
        chars: ['って', 'っか', 'っぱ', 'っさ'],
        reads: ['tte', 'kka', 'ppa', 'ssa'],
        note: 'っ crea pausa y duplica la consonante siguiente. Zasshi (revista) = ざっし. En hiragana el alargamiento usa la misma vocal: okaasan = おかあさん. En katakana usa el guion ー: keeki = ケーキ.',
      },
    ],
  },
  {
    id: 'm2',
    levelNum: 1,
    levelTitle: 'Nivel 1: Fundamentos Absolutos',
    block: 'I',
    bLabel: 'Alfabetización y Fonética',
    title: 'Módulo 2',
    sub: 'Katakana — Préstamos y Énfasis',
    color: '#98D96A',
    xpE: 200,
    req: 'm1',
    lessons: [
      {
        id: 'm2l1',
        t: 'ア行',
        s: 'a · i · u · e · o',
        xp: 40,
        chars: ['ア', 'イ', 'ウ', 'エ', 'オ'],
        reads: ['a', 'i', 'u', 'e', 'o'],
        note: 'Misma fonética que hiragana, trazos angulares y rectos. Katakana = extranjerismos, nombres y énfasis. Airon (plancha), Inku (tinta), Uinnaa (salchicha Viena), Epuron (delantal), Ootobai (moto).',
      },
      {
        id: 'm2l2',
        t: 'カ行',
        s: 'ka · ki · ku · ke · ko',
        xp: 40,
        chars: ['カ', 'キ', 'ク', 'ケ', 'コ'],
        reads: ['ka', 'ki', 'ku', 'ke', 'ko'],
        note: 'Kamera (cámara), Kiroguramu (kilogramo), Kureyon (crayón), Keeki (torta), Koohii (café). コーヒー = coffee — nota el guion largo ー que alarga la vocal. Caja abierta hacia la izquierda.',
      },
      {
        id: 'm2l3',
        t: 'サ行 — シ vs ツ',
        s: 'sa · shi · su · se · so',
        xp: 40,
        chars: ['サ', 'シ', 'ス', 'セ', 'ソ'],
        reads: ['sa', 'shi', 'su', 'se', 'so'],
        note: 'CLAVE: シ (shi) — los trazos miran HACIA ARRIBA, como alguien esquiando. Saboten (cactus), Shiisoo (subibaja), Surippa (pantuflas), Seroteepu (cinta), Sofa (sofá). Sakkaa = fútbol.',
      },
      {
        id: 'm2l4',
        t: 'タ行 — ツ vs シ',
        s: 'ta · chi · tsu · te · to',
        xp: 40,
        chars: ['タ', 'チ', 'ツ', 'テ', 'ト'],
        reads: ['ta', 'chi', 'tsu', 'te', 'to'],
        note: 'CLAVE: ツ (tsu) — los trazos miran HACIA ABAJO, aterrorizados por el tsunami. Taoru (toalla), Chiizu (queso), Tsuaa (tour), Tento (carpa), Toranpu (cartas). Terebi = TV.',
      },
      {
        id: 'm2l5',
        t: 'ナ行',
        s: 'na · ni · nu · ne · no',
        xp: 40,
        chars: ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ'],
        reads: ['na', 'ni', 'nu', 'ne', 'no'],
        note: 'Naifu (cuchillo), Nikoniko (sonrisa — dos líneas paralelas), Nu, Nekutai (corbata), Nooto (cuaderno — un trazo diagonal simple). ノ es la partícula の en katakana.',
      },
      {
        id: 'm2l6',
        t: 'ハ行',
        s: 'ha · hi · fu · he · ho',
        xp: 40,
        chars: ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ'],
        reads: ['ha', 'hi', 'fu', 'he', 'ho'],
        note: 'Hangaa (percha — forma de V), Hiitaa (estufa), Furaipan (sartén — gancho), Herumetto (casco — idéntico a へ hiragana), Hottokeeki (hotcake). Hoteru = hotel.',
      },
      {
        id: 'm2l7',
        t: 'マ行',
        s: 'ma · mi · mu · me · mo',
        xp: 40,
        chars: ['マ', 'ミ', 'ム', 'メ', 'モ'],
        reads: ['ma', 'mi', 'mu', 'me', 'mo'],
        note: 'Mafuraa (bufanda), Minikaa (auto pequeño — tres trazos diagonales), Muudo (ánimo/mood), Medaru (medalla — forma de X), Mootaabooto (barco motor). Manga = マンガ.',
      },
      {
        id: 'm2l8',
        t: 'ヤ行',
        s: 'ya · yu · yo',
        xp: 30,
        chars: ['ヤ', 'ユ', 'ヨ'],
        reads: ['ya', 'yu', 'yo'],
        note: 'Taiya (neumático), Yuufoo (OVNI), Yooyoo (yoyó — parece E invertida). Solo 3 caracteres como en hiragana. Yunifoomo = uniforme. Yooguruto = yogurt.',
      },
      {
        id: 'm2l9',
        t: 'ラ行',
        s: 'ra · ri · ru · re · ro',
        xp: 40,
        chars: ['ラ', 'リ', 'ル', 'レ', 'ロ'],
        reads: ['ra', 'ri', 'ru', 're', 'ro'],
        note: 'Raamen (ramen — nota ー para alargar), Ribon (listón/moño), Rubii (rubí), Reinkooto (impermeable), Rooraasukeeto (patines — cuadrado perfecto). Reberu = level.',
      },
      {
        id: 'm2l10',
        t: 'ワ行 · ヲ · ン — ン vs ソ',
        s: 'wa · wo · n',
        xp: 30,
        chars: ['ワ', 'ヲ', 'ン'],
        reads: ['wa', 'wo', 'n'],
        note: 'CLAVE: ン (n) tiene trazo largo HORIZONTAL. ソ (so) tiene trazo casi vertical. Nunca confundirlos. Waishatsu (camisa elegante), Wotagei (baile de fans), ン nunca inicia palabra. Wain = wine.',
      },
      {
        id: 'm2l11',
        t: 'Dakuon y Sonidos Especiales',
        s: 'ga · za · da · ba + fa · ti · va',
        xp: 50,
        chars: ['ガ', 'ザ', 'ダ', 'バ', 'ファ', 'ティ', 'ヴァ'],
        reads: ['ga', 'za', 'da', 'ba', 'fa', 'ti', 'va'],
        note: 'Misma lógica que hiragana con tenten. Sonidos especiales modernos: ティ (ti) en paatii (fiesta), ファ (fa) en sofa (ソファ), ウィ (wi), ヴァ (va). Solo katakana puede crear estos sonidos.',
      },
      {
        id: 'm2l12',
        t: 'Guion largo ー y Sokuon ッ',
        s: 'alargamiento · doble consonante',
        xp: 40,
        chars: ['コーヒー', 'スーパー', 'ベッド', 'ネット'],
        reads: ['koohii', 'suupaa', 'beddo', 'netto'],
        note: 'ー alarga la vocal anterior — exclusivo de katakana. ッ duplica consonante: beddo (cama), netto (internet). Detectar estos patrones es clave para leer préstamos del inglés en japonés.',
      },
    ],
  },
  {
    id: 'm3',
    levelNum: 2,
    levelTitle: 'Nivel 2: Gramática Elemental I',
    block: 'II',
    bLabel: 'Gramática Fundacional',
    title: 'Módulo 3',
    sub: 'Identidad · DESU · KOSOADO',
    color: '#7C3AED',
    xpE: 250,
    req: 'm2',
    lessons: [
      {
        id: 'm3l1',
        t: 'Partícula WA (は) y Cópula DESU',
        s: 'marcador de tema · afirmación · identidad',
        xp: 60,
        chars: ['は', 'です', 'わたし', 'じん'],
        reads: ['wa', 'desu', 'watashi', 'jin'],
        vocab: [
          { jp: 'わたし は ジョージ です', es: 'Yo soy George' },
          { jp: 'わたし は にほんじん です', es: 'Yo soy japonés' },
          { jp: 'エクアドル じん です', es: 'Soy ecuatoriano' },
          { jp: 'どうぞ よろしく', es: 'Mucho gusto' },
        ],
        note: "DESU es la cópula de cortesía formal ('ser/estar'). La partícula は (pronunciada WA como partícula) pone un foco sobre el tema de conversación: 'En cuanto a mí...'. Estructura básica japonesa: [Tema/Sujeto] は [Predicado] です.",
        objective: 'Dominar la estructura fundamental de afirmación e identidad utilizando la partícula は y la cópula です.',
        tables: [
          {
            title: 'Estructura Básica de la Oración Nominal',
            headers: ['Elemento', 'Japonés', 'Función', 'Ejemplo'],
            rows: [
              ['Tema', 'わたし は', 'Pone el foco de la oración ("En cuanto a...")', 'わたし は (Watashi wa)'],
              ['Predicado', 'がくせい', 'Información que describe al tema', 'がくせい (Estudiante)'],
              ['Cópula', 'です', 'Cortesía formal ("es / soy")', 'です (Desu)'],
            ],
          },
        ],
      },
      {
        id: 'm3l1b',
        t: 'Jikoshoukai y Honoríficos',
        s: 'presentación personal · -san · -kun · -sama',
        xp: 50,
        chars: ['さん', 'くん', 'さま'],
        reads: ['san', 'kun', 'sama'],
        vocab: [
          { jp: 'はじめまして', es: 'Mucho gusto (al conocer a alguien)' },
          { jp: 'わたし は [なまえ] です', es: 'Yo soy [nombre]' },
          { jp: 'よろしく おねがいします', es: 'Encantado / espero su buena disposición' },
        ],
        note: 'Protocolo de Jikoshoukai (自己紹介, presentación personal): Hajimemashite → Watashi wa [Nombre] desu → Yoroshiku onegaishimasu. Honoríficos: -san (respeto general, para cualquier persona), -kun (informal, para jóvenes u hombres cercanos), -sama (máxima cortesía, clientes o cartas formales). Regla de oro: NUNCA uses un honorífico con tu propio nombre — sería como auto-alabarte.',
        objective: 'Dominar la estructura estándar de presentación personal y el uso adecuado de los sufijos honoríficos.',
        tables: [
          {
            title: 'Protocolo de Presentación (Jikoshoukai)',
            headers: ['Paso', 'Japonés', 'Romaji', 'Función Social'],
            rows: [
              ['1. Apertura', 'はじめまして', 'hajimemashite', 'Mucho gusto (solo al conocer por 1ª vez)'],
              ['2. Nombre', 'わたし は [名前] です', 'watashi wa [name] desu', 'En cuanto a mí, soy [Nombre]'],
              ['3. Cierre', 'よろしく おねがいします', 'yoroshiku onegaishimasu', 'Trátame bien / Encantado de conocerte'],
            ],
          },
        ],
      },
      {
        id: 'm3l2',
        t: 'Partícula MO (も) — Inclusión ("También")',
        s: 'inclusión · también · sustitución de WA',
        xp: 60,
        chars: ['も', 'かれ', 'かのじょ', 'ともだち'],
        reads: ['mo', 'kare', 'kanojo', 'tomodachi'],
        vocab: [
          { jp: 'たなかさん も にほんじん です', es: 'Tanaka también es japonés' },
          { jp: 'わたし も がくせい です', es: 'Yo también soy estudiante' },
          { jp: 'かれ も ともだち です', es: 'Él también es mi amigo' },
        ],
        note: "La partícula MO (も) significa 'también' o 'tampoco'. REGLA CLAVE: MO sustituye completamente a la partícula WA (は). Nunca se dice 'wa mo', simplemente se reemplaza por 'MO' para indicar que lo anterior también aplica.",
        objective: 'Expresar inclusión y coincidencia sustituyendo correctamente la partícula WA por MO.',
        pitchNote: {
          pattern: 'Heiban',
          desc: 'Las partículas (wa, mo) no llevan acento tonal propio; adoptan el tono final de la palabra precedente.',
          example: 'わたし も (watashi mo)',
        },
      },
      {
        id: 'm3l3',
        t: 'Partícula NO (の) — Posesión y Profesiones',
        s: 'posesión · pertenencia · profesiones',
        xp: 50,
        chars: ['の', 'ほん', 'せんせい', 'がくせい', 'かいしゃいん', 'いしゃ'],
        reads: ['no', 'hon', 'sensei', 'gakusei', 'kaishain', 'isha'],
        vocab: [
          { jp: 'わたし の ほん', es: 'Mi libro (libro de mi propiedad)' },
          { jp: 'にほんご の せんせい', es: 'Profesor de japonés' },
          { jp: 'ナルト の せんせい は かかし です', es: 'El profesor de Naruto es Kakashi' },
          { jp: 'わたし は いしゃ です', es: 'Yo soy médico' },
        ],
        note: "NO (の) conecta dos sustantivos. El primer sustantivo posee o califica al segundo: [Poseedor] の [Objeto poseído]. Ej: 'Watashi no hon' = mi libro. Profesiones: Sensei (profesor), Gakusei (estudiante), Kaishain (empleado), Isha (médico).",
        objective: 'Conectar sustantivos para expresar posesión, pertenencia y especialización utilizando la partícula NO.',
      },
      {
        id: 'm3l4',
        t: 'Partícula KA (か) — Preguntas e Interrogación',
        s: 'interrogación · dudas · preguntas con DESU',
        xp: 50,
        chars: ['か', 'だれ', 'なん', 'ちがいます'],
        reads: ['ka', 'dare', 'nan', 'chigaimasu'],
        vocab: [
          { jp: 'あなた は がくせい です か', es: '¿Tú eres estudiante?' },
          { jp: 'これ は なん です か', es: '¿Qué es esto?' },
          { jp: 'あの ひと は だれ です か', es: '¿Quién es aquella persona?' },
          { jp: 'いいえ ちがいます', es: 'No, es diferente / no es así' },
        ],
        note: "La partícula KA (か) colocada al final de una oración la transforma inmediatamente en pregunta, actuando como un signo de interrogación verbal. No es necesario cambiar la entonación de la frase. Preguntas clave: Dare (¿Quién?), Nan/Nani (¿Qué?).",
        objective: 'Formular y responder preguntas formales cerradas y abiertas utilizando la partícula KA.',
      },
      {
        id: 'm3l5',
        t: 'Partículas NI (に) y DE (で) — Destino y Medio',
        s: 'dirección · destino · medio de transporte · lugar de acción',
        xp: 50,
        chars: ['に', 'で', 'がっこう', 'いきます'],
        reads: ['ni', 'de', 'gakkou', 'ikimasu'],
        vocab: [
          { jp: 'がっこう に いきます', es: 'Voy a la escuela' },
          { jp: 'がっこう へ いきます', es: 'Voy hacia la escuela' },
          { jp: 'ともだち と ゲーム を します', es: 'Juego videojuegos con amigos' },
        ],
        note: "DISTINCIÓN CRÍTICA: NI (に) marca el destino o punto de llegada de un movimiento ('a la escuela'). DE (で) marca el medio o herramienta con que se realiza algo ('en autobús') o el lugar donde ocurre una acción activa.",
        objective: 'Diferenciar el uso de la partícula de destino NI frente a la partícula de medio o lugar DE.',
      },
      {
        id: 'm3l6',
        t: 'KOSOADO — Objetos',
        s: 'kore · sore · are · kono · sono · ano',
        xp: 60,
        chars: ['これ', 'それ', 'あれ', 'どれ', 'この', 'その', 'あの', 'どの'],
        reads: ['kore', 'sore', 'are', 'dore', 'kono', 'sono', 'ano', 'dono'],
        vocab: [
          { jp: 'これ は ポケモン の カード です', es: 'Esto es una carta de Pokémon' },
          { jp: 'あれ は マリオ です', es: 'Eso de allá es Mario' },
        ],
        note: 'KO=cerca mío, SO=cerca de ti, A=lejos de ambos, DO=pregunta. REGLA: Kore/Sore/Are REEMPLAZAN al sustantivo. Kono/Sono/Ano ACOMPAÑAN al sustantivo (Ej: Kono kagi = esta llave). Nunca solos.',
        objective: 'Dominar la matriz de pronombres y adjetivos demostrativos según la distancia física y psicológica.',
        tables: [
          {
            title: 'Matriz Demostrativa KOSOADO (Objetos)',
            headers: ['Distancia', 'Pronombre (Solo)', 'Adjetivo (+ Sustantivo)'],
            rows: [
              ['Cerca del Hablante (KO)', 'これ (Kore - Esto)', 'この [名詞] (Kono - Este...)'],
              ['Cerca del Oyente (SO)', 'それ (Sore - Eso)', 'その [名詞] (Sono - Ese...)'],
              ['Lejos de Ambos (A)', 'あれ (Are - Aquello)', 'あの [名詞] (Ano - Aquel...)'],
              ['Pregunta / Incógnita (DO)', 'どれ (Dore - ¿Cuál?)', 'どの [名詞] (Dono - ¿Cuál...?)'],
            ],
          },
        ],
      },
      {
        id: 'm3l7',
        t: 'KOSOADO — Lugares',
        s: 'koko · soko · asoko · doko',
        xp: 50,
        chars: [
          'ここ',
          'そこ',
          'あそこ',
          'どこ',
          'こちら',
          'そちら',
          'あちら',
          'どちら',
        ],
        reads: [
          'koko',
          'soko',
          'asoko',
          'doko',
          'kochira',
          'sochira',
          'achira',
          'dochira',
        ],
        vocab: [
          { jp: 'トイレ は どこ です か', es: '¿Dónde está el baño?' },
          { jp: 'ここ は ハイラル です', es: 'Aquí es Hyrule' },
        ],
        note: "Misma lógica KO-SO-A-DO para lugares. こちら/そちら son versiones formales. La frase más útil en Japón: 'トイレはどこですか' (¿Dónde está el baño?). Si la llave está cerca de tu amigo: sore/sono.",
        objective: 'Preguntar y responder la ubicación de lugares de interés e instalaciones urbanas.',
      },
    ],
  },
{
    id: 'm4',
    levelNum: 2,
    levelTitle: 'Nivel 2: Gramática Elemental I',
    block: 'II',
    bLabel: 'Gramática Fundacional',
    title: 'Módulo 4',
    sub: 'Números · Contadores · Tiempo · Calendario',
    color: '#12A8C2',
    xpE: 300,
    req: 'm3',
    lessons: [
      {
        id: 'm4l1',
        t: 'Números 1–10 (Unidades Base)',
        s: 'ichi · ni · san · yon · go · roku · nana · hachi · kyuu · juu',
        xp: 60,
        chars: ['いち', 'に', 'さん', 'よん', 'ご', 'ろく', 'なな', 'はち', 'きゅう', 'じゅう'],
        reads: ['ichi', 'ni', 'san', 'yon', 'go', 'roku', 'nana', 'hachi', 'kyuu', 'juu'],
        vocab: [
          { jp: 'わたし の でんわばんごう は いち に さん です', es: 'Mi número de teléfono es 1-2-3' },
          { jp: 'ドラゴンボール は なな こ あります', es: 'Hay 7 esferas del dragón' },
        ],
        note: 'Evita el tabú del número 4 (shi) y 7 (shichi) por asociación fonética con muerte (死 shi) — en el habla cotidiana se prefiere YON y NANA.',
        objective: 'Dominar la pronunciación y reconocimiento de las 10 cifras elementales japonesas.',
        tables: [
          {
            title: 'Tabla de Cifras Fundamentales (1–10)',
            headers: ['Número', 'Hiragana', 'Romaji', 'Clave Mnemotécnica'],
            rows: [
              ['1', 'いち', 'ichi', 'Ichigo (Bleach) / Número Uno'],
              ['2', 'に', 'ni', 'Nii-san (Hermano mayor)'],
              ['3', 'さん', 'san', 'Sanji (One Piece)'],
              ['4', 'よん', 'yon', 'Yonko (Los 4 Emperadores)'],
              ['5', 'ご', 'go', 'Goku (Dragon Ball)'],
              ['6', 'ろく', 'roku', 'Rock Lee (Naruto)'],
              ['7', 'なな', 'nana', '7 Esferas del Dragón'],
              ['8', 'はち', 'hachi', 'Hachiko (Shibuya)'],
              ['9', 'きゅう', 'kyuu', 'Kyuubi (Zorro de 9 Colas)'],
              ['10', 'じゅう', 'juu', 'Jujutsu Kaisen'],
            ],
          },
        ],
      },
      {
        id: 'm4l2',
        t: 'Contadores Esenciales (〜つ y 〜個)',
        s: 'hitotsu · futatsu · mittsu · ikko · niko',
        xp: 60,
        chars: ['ひとつ', 'ふたつ', 'みっつ', 'よっつ', 'いつつ', 'いっこ', 'にこ', 'さんこ', 'いくつ'],
        reads: ['hitotsu', 'futatsu', 'mittsu', 'yottsu', 'itsutsu', 'ikko', 'niko', 'sanko', 'ikutsu'],
        vocab: [
          { jp: 'これ を ひとつ ください', es: 'Deme uno de estos por favor' },
          { jp: 'りんご を にこ ください', es: 'Deme dos manzanas por favor' },
          { jp: 'いくつ あります か', es: '¿Cuántos hay?' },
        ],
        note: 'En japonés los objetos no se cuentan solos: usan sufijos contadores. 〜つ (tsu) es el contador nativo general (1-10); 〜個 (ko) es para objetos tridimensionales pequeños.',
        objective: 'Solicitar cantidades específicas de objetos en contextos cotidianos de tiendas y restaurantes.',
      },
      {
        id: 'm4l3',
        t: 'Decenas y Edad (11–99 / 〜歳)',
        s: 'juuichi · nijuu · sanjuu · sai · hatachi',
        xp: 60,
        chars: ['じゅういち', 'にじゅう', 'にじゅうご', 'さんじゅう', 'よんじゅう', 'ごじゅう', 'さい', 'はたち', 'なんさい'],
        reads: ['jūichi', 'nijū', 'nijūgo', 'sanjū', 'yonjū', 'gojū', 'sai', 'hatachi', 'nansai'],
        vocab: [
          { jp: 'かれ は にじゅう ご さい です', es: 'Él tiene 25 años de edad' },
          { jp: 'わたし は はたち です', es: 'Yo tengo 20 años (mayoría de edad)' },
          { jp: 'あなた は なんさい です か', es: '¿Cuántos años tienes?' },
        ],
        note: 'La regla es matemática pura: Decena + Unidad (25 = Ni-juu-go). Excepción cultural única: 20 años se dice HATACHI (marca la mayoría de edad tradicional en Japón).',
        objective: 'Preguntar y expresar la edad propia y ajena con precisión formal.',
      },
      {
        id: 'm4l4',
        t: 'Centenas, Miles y Dinero (100–10.000 / 円)',
        s: 'hyaku · sen · ichiman · en',
        xp: 70,
        chars: ['ひゃく', 'さんびゃく', 'ろっぴゃく', 'はっぴゃく', 'せん', 'さんぜん', 'はっせん', 'いちまん', 'えん'],
        reads: ['hyaku', 'sanbyaku', 'roppyaku', 'happyaku', 'sen', 'sanzen', 'hassen', 'ichiman', 'en'],
        vocab: [
          { jp: 'ひゃく えん です', es: 'Son 100 yenes' },
          { jp: 'さんぜん えん です', es: 'Son 3.000 yenes' },
          { jp: 'いちまん えん です', es: 'Son 10.000 yenes (1 Man)' },
        ],
        note: 'Cuidado con las irregularidades fonéticas: 300 (sanbyaku), 600 (roppyaku), 800 (happyaku), 3.000 (sanzen), 8.000 (hassen). En Japón se agrupa por unidades de 10.000 (万 MAN).',
        objective: 'Manejar cifras monetarias y transacciones financieras en yenes con soltura auditiva y visual.',
      },
      {
        id: 'm4l5',
        t: 'Compras y Precios (Ikura desu ka?)',
        s: 'ikura · kaimono · kore · kudasai',
        xp: 60,
        chars: ['いくら', 'かいもの', 'これ', 'それ', 'あれ', 'えん', 'ください'],
        reads: ['ikura', 'kaimono', 'kore', 'sore', 'are', 'en', 'kudasai'],
        vocab: [
          { jp: 'これ は いくら です か', es: '¿Cuánto cuesta esto?' },
          { jp: 'それ は ごひゃく えん です', es: 'Eso cuesta 500 yenes' },
          { jp: 'これ を ください', es: 'Por favor deme este' },
        ],
        note: 'La fórmula reina de compras en Japón: [Objeto] は いくら です か (¿Cuánto cuesta [X]?). Para comprar: [Objeto] を ください (Deme [X] por favor).',
        objective: 'Preguntar precios y realizar compras de artículos en comercios de Japón.',
      },
      {
        id: 'm4l6',
        t: 'La Hora Exacta (〜時 y 〜分)',
        s: 'ji · fun · pun · han · gozen · gogo · nanji',
        xp: 60,
        chars: ['じ', 'ふん', 'ぷん', 'はん', 'ごぜん', 'ごご', 'いま', 'なんじ'],
        reads: ['ji', 'fun', 'pun', 'han', 'gozen', 'gogo', 'ima', 'nanji'],
        vocab: [
          { jp: 'いま なんじ です か', es: '¿Qué hora es ahora?' },
          { jp: 'ごご さん じ はん です', es: 'Son las 3 y media de la tarde' },
          { jp: 'ごぜん じゅう じ です', es: 'Son las 10 de la mañana' },
        ],
        note: 'Horas: número + JI. Excepciones: 4=yoji, 7=shichiji, 9=kuji. Minutos usan FUN/PUN (1,3,4,6,8,10 son PUN: ippun, sanpun, roppun). はん (han) = y media.',
        objective: 'Decir y consultar la hora exacta con discriminación de minutos regulares e irregulares.',
      },
      {
        id: 'm4l7',
        t: 'Los 7 Días de la Semana (〜曜日)',
        s: 'getsuyoubi · kayoubi · suiyoubi · mokuyoubi · kinyoubi · doyoubi · nichiyoubi',
        xp: 60,
        chars: ['げつようび', 'かようび', 'すいようび', 'もくようび', 'きんようび', 'どようび', 'にちようび'],
        reads: ['getsuyoubi', 'kayoubi', 'suiyoubi', 'mokuyoubi', 'kinyoubi', 'doyoubi', 'nichiyoubi'],
        vocab: [
          { jp: 'きょう は もくようび です', es: 'Hoy es jueves' },
          { jp: 'にちようび に いきます', es: 'Iré el domingo' },
          { jp: 'げつようび から きんようび まで です', es: 'Es de lunes a viernes' },
        ],
        note: 'Los días llevan el nombre de los 7 cuerpos celestes y elementos naturales: Lunes=Luna (Getsu), Martes=Fuego (Ka), Miércoles=Agua (Sui), Jueves=Madera (Moku), Viernes=Metal/Oro (Kin), Sábado=Tierra (Do), Domingo=Sol (Nichi).',
        objective: 'Programar citas y actividades a lo largo de los días de la semana.',
      },
      {
        id: 'm4l8',
        t: 'El Calendario (Días Irregulares y Meses)',
        s: 'tsuitachi · futsuka · mikka · hatsuka · tanjoubi · gatsu',
        xp: 70,
        chars: ['ついたち', 'ふつか', 'みっか', 'よっか', 'いつか', 'はつか', 'たんじょうび', 'いちがつ', 'なんがつ'],
        reads: ['tsuitachi', 'futsuka', 'mikka', 'yokka', 'itsuka', 'hatsuka', 'tanjoubi', 'ichigatsu', 'nangatsu'],
        vocab: [
          { jp: 'たんじょうび は いつ です か', es: '¿Cuándo es tu cumpleaños?' },
          { jp: 'いちがつ ついたち です', es: 'Es el primero de enero' },
          { jp: 'ごがつ はつか です', es: 'Es el 20 de mayo' },
        ],
        note: 'Los primeros 10 días del mes y el día 20 tienen lecturas ancestrales nativas irregulares (Tsuitachi, Futsuka, Mikka, Yokka, Itsuka, Muika, Nanoka, Youka, Kokonoka, Tooka, Hatsuka). Los meses son simples: Número + GATSU.',
        objective: 'Expresar fechas de nacimiento y eventos en el calendario japonés.',
      },
    ],
  },
  {
    id: 'm5',
    levelNum: 3,
    levelTitle: 'Nivel 3: Gramática Elemental II',
    block: 'III',
    bLabel: 'Dinámica Verbal',
    title: 'Módulo 5',
    sub: 'Verbos · Conjugación MASU · Rutina y Acción',
    color: '#10B981',
    xpE: 350,
    req: 'm4',
    lessons: [
      {
        id: 'm5l1',
        t: 'Los 3 Grupos de Verbos (Godan, Ichidan, Irregulares)',
        s: 'u-verbs · ru-verbs · suru · kuru',
        xp: 70,
        chars: ['かく', 'のむ', 'みる', 'たべる', 'する', 'くる'],
        reads: ['kaku', 'nomu', 'miru', 'taberu', 'suru', 'kuru'],
        vocab: [
          { jp: 'まんが を かく', es: 'Escribo / dibujo un manga' },
          { jp: 'ラーメン を たべる', es: 'Como ramen' },
          { jp: 'べんきょう を する', es: 'Hago estudio / estudio' },
        ],
        note: 'Clasificación anatómica de los verbos: Grupo 1 (Godan/-u), Grupo 2 (Ichidan/-ru precedido de e/i), Grupo 3 (los 2 únicos irregulares: SURU = hacer, KURU = venir).',
        objective: 'Identificar el grupo morfológico de cualquier verbo para aplicar conjugaciones correctas.',
      },
      {
        id: 'm5l2',
        t: 'Forma MASU — Presente y Futuro Formal',
        s: 'kakimasu · nomimasu · tabemasu · mimasu · shimasu',
        xp: 70,
        chars: ['かきます', 'のみます', 'たべます', 'みます', 'します', 'きます'],
        reads: ['kakimasu', 'nomimasu', 'tabemasu', 'mimasu', 'shimasu', 'kimasu'],
        vocab: [
          { jp: 'みず を のみます', es: 'Bebo agua' },
          { jp: 'アニメ を みます', es: 'Veo anime' },
          { jp: 'にほん へ きます', es: 'Vengo a Japón' },
        ],
        note: 'Regla del Cambio Vocálico: Grupo 1 cambia la terminación -u por -i + MASU (Kaku → Kakimasu, Nomu → Nomimasu). Grupo 2 elimina -ru + MASU (Taberu → Tabemasu).',
        objective: 'Construir oraciones afirmativas en registro de cortesía formal (Teinei-go).',
      },
      {
        id: 'm5l3',
        t: 'Negación Verbal (〜MASEN)',
        s: 'tabemasen · nomimasen · ikimasen · shimasen',
        xp: 60,
        chars: ['たべません', 'のみません', 'いきません', 'しません', 'みません'],
        reads: ['tabemasen', 'nomimasen', 'ikimasen', 'shimasen', 'mimasen'],
        vocab: [
          { jp: 'おさけ を のみません', es: 'No bebo alcohol' },
          { jp: 'あした は がっこう へ いきません', es: 'Mañana no voy a la escuela' },
          { jp: 'テレビ を みません', es: 'No veo televisión' },
        ],
        note: 'Para negar en presente/futuro formal, se reemplaza MASU por MASEN. Sencillo, limpio y directo: Tabemasu (como) → Tabemasen (no como).',
        objective: 'Expresar negaciones y hábitos que no se realizan.',
      },
      {
        id: 'm5l4',
        t: 'Tiempo Pasado (〜MASHITA y 〜MASEN DESHITA)',
        s: 'tabemashita · nomimashita · ikimashita · masendeshita',
        xp: 70,
        chars: ['たべました', 'のみました', 'いきました', 'しました', 'たべませんでした', 'のみませんでした'],
        reads: ['tabemashita', 'nomimashita', 'ikimashita', 'shimashita', 'tabemasendeshita', 'nomimasendeshita'],
        vocab: [
          { jp: 'きのう ラーメン を たべました', es: 'Ayer comí ramen' },
          { jp: 'にほん へ いきました', es: 'Fui a Japón' },
          { jp: 'きのう は べんきょう しませんでした', es: 'Ayer no estudié' },
        ],
        note: 'Pasado afirmativo: -MASHITA (hice). Pasado negativo: -MASEN DESHITA (no hice). Lengua aglutinante: la raíz nunca se deforma.',
        objective: 'Relatar eventos y acciones completadas en el pasado.',
      },
      {
        id: 'm5l5',
        t: 'Expresar Deseo (〜TAI DESU / 〜TAKUNAI DESU)',
        s: 'tabetai · nomitai · ikitai · shitai',
        xp: 60,
        chars: ['たべたい', 'のみたい', 'いきたい', 'したい', 'たいです', 'たくないです'],
        reads: ['tabetai', 'nomitai', 'ikitai', 'shitai', 'taidesu', 'takunaidesu'],
        vocab: [
          { jp: 'にほん へ いきたい です', es: 'Quiero ir a Japón' },
          { jp: 'すし を たべたい です', es: 'Quiero comer sushi' },
          { jp: 'ゲーム を したい です', es: 'Quiero jugar videojuegos' },
        ],
        note: 'Se quita MASU y se añade -TAI DESU para expresar deseos propios: "Quiero hacer X". Para decir "No quiero": -TAKUNAI DESU.',
        objective: 'Comunicar deseos, intenciones y preferencias personales en primera persona.',
      },
      {
        id: 'm5l6',
        t: 'Partícula WO (を) — Acciones sobre Objetos',
        s: 'objeto directo · comer · beber · leer · comprar',
        xp: 60,
        chars: ['を', 'ごはん', 'パン', 'おちゃ', 'みず', 'かいます', 'よみます'],
        reads: ['wo', 'gohan', 'pan', 'ocha', 'mizu', 'kaimasu', 'yomimasu'],
        vocab: [
          { jp: 'ごはん を たべます', es: 'Como arroz / comida' },
          { jp: 'ほん を よみます', es: 'Leo un libro' },
          { jp: 'パン を かいます', es: 'Compro pan' },
        ],
        note: 'La partícula を (pronunciada O) marca el objeto directo sobre el que recae la acción del verbo transitivo: [Objeto] を [Verbo].',
        objective: 'Construir oraciones transitivas fluidas en orden Sujeto-Objeto-Verbo.',
      },
      {
        id: 'm5l7',
        t: 'Movimiento y Espacio (Partículas HE, NI, DE)',
        s: 'he · ni · de · densha · eki · ikimasu',
        xp: 60,
        chars: ['へ', 'に', 'で', 'でんしゃ', 'えき', 'いきます', 'きます'],
        reads: ['e', 'ni', 'de', 'densha', 'eki', 'ikimasu', 'kimasu'],
        vocab: [
          { jp: 'えき へ いきます', es: 'Voy hacia la estación' },
          { jp: 'でんしゃ で いきます', es: 'Voy en tren' },
          { jp: 'いえ で べんきょう します', es: 'Estudio en mi casa' },
        ],
        note: 'へ (leída E) marca dirección general. に marca destino exacto. で marca medio de transporte ("en tren") o lugar donde ocurre la acción activa.',
        objective: 'Describir trayectos de desplazamiento y medios de locomoción urbana.',
      },
      {
        id: 'm5l8',
        t: 'Existencia Viva vs Inanimada (ARIMASU vs IMASU)',
        s: 'arimasu · imasu · tsukue · neko · inu',
        xp: 60,
        chars: ['あります', 'います', 'つくえ', 'ねこ', 'いぬ', 'ともだち'],
        reads: ['arimasu', 'imasu', 'tsukue', 'neko', 'inu', 'tomodachi'],
        vocab: [
          { jp: 'つくえ が あります', es: 'Hay un escritorio (objeto inanimado)' },
          { jp: 'ねこ が います', es: 'Hay un gato (ser vivo)' },
          { jp: 'ともだち が います', es: 'Está mi amigo / Tengo amigos' },
        ],
        note: 'Regla de oro ontológica: あります es para cosas inanimadas (plantas, mesas, dinero); います es para seres vivos con movimiento autónomo (personas, animales).',
        objective: 'Expresar existencia y posesión diferenciando seres vivos de objetos inanimados.',
      },
    ],
  },
  {
    id: 'm6',
    levelNum: 4,
    levelTitle: 'Nivel 4: Adquisición Sinográfica & Cualidades',
    block: 'IV',
    bLabel: 'Adjetivos y Calificación',
    title: 'Módulo 6',
    sub: 'Adjetivos Tipo I y NA · Estados · Gustos · Colores',
    color: '#F59E0B',
    xpE: 350,
    req: 'm5',
    lessons: [
      {
        id: 'm6l1',
        t: 'Adjetivos Tipo I (い-Keiyoushi) — Afirmación y Negación',
        s: 'takai · yasui · ookii · chiisai · oishii · takakunai',
        xp: 70,
        chars: ['たかい', 'やすい', 'おおきい', 'ちいさい', 'おいしい', 'たかくない', 'おいしくない'],
        reads: ['takai', 'yasui', 'ookii', 'chiisai', 'oishii', 'takakunai', 'oishikunai'],
        vocab: [
          { jp: 'この ラーメン は おいしい です', es: 'Este ramen es delicioso' },
          { jp: 'この ほん は たかくない です', es: 'Este libro no es caro' },
          { jp: 'くるま は やすい です', es: 'El auto es barato' },
        ],
        note: 'Los adjetivos Tipo I terminan en "i" pura. Método del Kunai: para negar se corta la "i" final y se agrega -KUNAI (Takai → Takakunai).',
        objective: 'Calificar sustantivos en presente afirmativo y negativo con adjetivos Tipo I.',
      },
      {
        id: 'm6l2',
        t: 'Pasado de Adjetivos Tipo I (〜KATTA / 〜KUNAKATTA)',
        s: 'oishikatta · takakatta · takakunakatta',
        xp: 70,
        chars: ['おいしかった', 'たかかった', 'たかくなかった', 'あたらしい', 'ふるい'],
        reads: ['oishikatta', 'takakatta', 'takakunakatta', 'atarashii', 'furui'],
        vocab: [
          { jp: 'きのう の すし は おいしかった です', es: 'El sushi de ayer estuvo delicioso' },
          { jp: 'その ゲーム は たかくなかった です', es: 'Ese videojuego no fue caro' },
          { jp: 'この まんが は あたらしい です', es: 'Este manga es nuevo' },
        ],
        note: 'Pasado afirmativo: se cambia la "i" final por -KATTA (Oishii → Oishikatta). Pasado negativo: -KUNAKATTA (Takai → Takakunakatta).',
        objective: 'Evaluar experiencias y objetos en tiempo pasado.',
      },
      {
        id: 'm6l3',
        t: 'Adjetivos Tipo NA (な-Keiyoushi)',
        s: 'kirei · shizuka · genki · yuumei',
        xp: 60,
        chars: ['きれい', 'しずか', 'げんき', 'ゆうめい'],
        reads: ['kirei', 'shizuka', 'genki', 'yūmei'],
        vocab: [
          { jp: 'この まち は しずか です', es: 'Esta ciudad es tranquila' },
          { jp: 'せんせい は げんき です', es: 'El profesor está lleno de energía' },
          { jp: 'ナルト は ゆうめい です', es: 'Naruto es famoso' },
        ],
        note: 'Los adjetivos Tipo NA funcionan gramaticalmente como sustantivos. Al final de la oración se conjugan con DESU / JA ARIMASEN (no usan kunai). Cuidado: KIREI termina en "i" pero es Tipo NA.',
        objective: 'Describir cualidades de personas, lugares y entornos con adjetivos Tipo NA.',
      },
      {
        id: 'm6l4',
        t: 'Modificar Sustantivos Directamente',
        s: 'oishii tabemono · kirei na hito · yuumei na machi',
        xp: 60,
        chars: ['おいしい', 'おおきい', 'きれい', 'しずか', 'ゆうめい', 'ひと'],
        reads: ['oishii', 'ookii', 'kirei', 'shizuka', 'yūmei', 'hito'],
        vocab: [
          { jp: 'おいしい ごはん を たべます', es: 'Como comida deliciosa' },
          { jp: 'きれい な まち です', es: 'Es una ciudad hermosa' },
          { jp: 'ゆうめい な ひと です', es: 'Es una persona famosa' },
        ],
        note: 'Para poner el adjetivo antes del sustantivo: Tipo I va directo (Oishii gohan); Tipo NA OBLIGA a colocar "な" entre el adjetivo y el sustantivo (Kirei NA hito).',
        objective: 'Construir frases nominales complejas anteponiendo adjetivos calificativos.',
      },
      {
        id: 'm6l5',
        t: 'Gustos y Disgustos (SUKI y KIRAI con GA)',
        s: 'suki · kirai · daisuki · anime · manga',
        xp: 60,
        chars: ['すき', 'きらい', 'だいすき', 'アニメ', 'まんが', 'すし'],
        reads: ['suki', 'kirai', 'daisuki', 'anime', 'manga', 'sushi'],
        vocab: [
          { jp: 'わたし は アニメ が すき です', es: 'A mí me gusta el anime' },
          { jp: 'すし が だいすき です', es: 'Me encanta el sushi' },
          { jp: 'べんきょう が きらい です', es: 'Me disgusta estudiar' },
        ],
        note: 'Regla de Oro: SUKI y KIRAI son adjetivos NA, no verbos. Por eso lo que te gusta NO se marca con を sino con la partícula が (Anime GA suki desu).',
        objective: 'Expresar aficiones, gustos y aversiones personales de forma natural.',
      },
      {
        id: 'm6l6',
        t: 'Habilidades y Destrezas (JOUZU y HETA)',
        s: 'jouzu · heta · nihongo · game',
        xp: 60,
        chars: ['じょうず', 'へた', 'にほんご', 'にほんじん'],
        reads: ['jōzu', 'heta', 'nihongo', 'nihonjin'],
        vocab: [
          { jp: 'あなた は にほんご が じょうず です', es: 'Eres muy bueno en japonés' },
          { jp: 'わたし は ゲーム が へた です', es: 'Soy malo jugando videojuegos' },
        ],
        note: 'JOUZU (hábil/bueno) y HETA (torpe/malo) también usan が para marcar la habilidad: [Habilidad] が じょうず です. Nota de etiqueta: nunca uses jouzu para elogiarte a ti mismo.',
        objective: 'Describir talentos y destrezas prácticas en diversas actividades.',
      },
      {
        id: 'm6l7',
        t: 'Colores y Sensaciones Visuales',
        s: 'aka · ao · shiro · kuro · midori · kiiro',
        xp: 60,
        chars: ['あか', 'あお', 'しろ', 'くろ', 'みどり', 'きいろ', 'ちゃいろ', 'むらさき'],
        reads: ['aka', 'ao', 'shiro', 'kuro', 'midori', 'kiiro', 'chairo', 'murasaki'],
        vocab: [
          { jp: 'あか い くるま です', es: 'Es un auto rojo' },
          { jp: 'あお い そら です', es: 'Es un cielo azul' },
          { jp: 'しろ と くろ です', es: 'Es blanco y negro' },
        ],
        note: 'Los 4 colores básicos ancestrales (aka, ao, shiro, kuro) pueden funcionar como adjetivos I agregando -i (akai, aoi, shiroi, kuroi). El resto usan "no" (midori no).',
        objective: 'Identificar y describir objetos según su espectro cromático.',
      },
    ],
  },
  {
    id: 'm7',
    levelNum: 5,
    levelTitle: 'Nivel 5: Sinogramas y Raíces Kanji',
    block: 'V',
    bLabel: 'Kanji N5 Fundacional',
    title: 'Módulo 7',
    sub: 'Ideogramas · Radicales · Compuestos Jukugo',
    color: '#B14AE2',
    xpE: 400,
    req: 'm6',
    lessons: [
      {
        id: 'm7l1',
        t: 'Anatomía del Kanji (Onyomi, Kunyomi y Radicales)',
        s: 'onyomi · kunyomi · radicales · piezas de lego',
        xp: 80,
        chars: ['日', '月', '人', '大', '中', '小'],
        reads: ['nichi', 'getsu', 'hito', 'dai', 'chuu', 'shou'],
        vocab: [
          { jp: 'にちようび', es: 'Domingo (Día del Sol)' },
          { jp: 'あの ひと は だれ です か', es: '¿Quién es aquella persona?' },
          { jp: 'おおきい です', es: 'Es grande' },
        ],
        note: 'Onyomi = lectura china (para compuestos de 2+ kanji). Kunyomi = lectura japonesa nativa (cuando el kanji está solo o con okurigana). Los radicales son las piezas de LEGO conceptuales.',
        objective: 'Diferenciar lecturas chinas y japonesas mediante el reconocimiento de radicales.',
      },
      {
        id: 'm7l2',
        t: 'Los Elementos de la Naturaleza (日, 月, 火, 水, 木, 金, 土)',
        s: 'fuego · agua · madera · metal · tierra',
        xp: 80,
        chars: ['日', '月', '火', '水', '木', '金', '土'],
        reads: ['nichi', 'getsu', 'ka', 'sui', 'moku', 'kin', 'do'],
        vocab: [
          { jp: 'かようび', es: 'Martes (Día del Fuego)' },
          { jp: 'すいようび', es: 'Miércoles (Día del Agua)' },
          { jp: 'きんようび', es: 'Viernes (Día del Oro / Dinero)' },
        ],
        note: 'Estos 7 caracteres gobiernan el cosmos y los días de la semana. Representan la base ideográfica más frecuente de todo el sistema N5.',
        objective: 'Dominar la lectura y significado de los sinogramas elementales de la naturaleza.',
      },
      {
        id: 'm7l3',
        t: 'Posición, Tamaño y Dimensiones (大, 小, 中, 上, 下, 山, 川)',
        s: 'dai · shou · chuu · jou · ka · san · sen',
        xp: 80,
        chars: ['大', '小', '中', '上', '下', '山', '川'],
        reads: ['dai', 'shou', 'chuu', 'jou', 'ka', 'san', 'sen'],
        vocab: [
          { jp: 'ふじさん', es: 'Monte Fuji (Montaña Fuji)' },
          { jp: 'ちゅうごく', es: 'China (País del Centro)' },
          { jp: 'かわ', es: 'Río natural' },
        ],
        note: 'Caracteres pictográficos puros: 大 (persona con brazos abiertos = grande), 上 (línea sobre la base = arriba), 下 (línea bajo la base = abajo), 川 (tres corrientes de agua = río).',
        objective: 'Ubicar espacialmente elementos geográficos y magnitudes mediante kanji.',
      },
      {
        id: 'm7l4',
        t: 'Personas, Vida y Roles (人, 子, 女, 男, 先, 生)',
        s: 'hito · ko · onna · otoko · sen · sei',
        xp: 80,
        chars: ['人', '子', '女', '男', '先', '生'],
        reads: ['hito', 'ko', 'onna', 'otoko', 'sen', 'sei'],
        vocab: [
          { jp: 'せんせい', es: 'Profesor (nacido antes)' },
          { jp: 'がくせい', es: 'Estudiante (quien estudia la vida)' },
          { jp: 'おんな の こ', es: 'Niña' },
          { jp: 'おとこ の こ', es: 'Niño' },
        ],
        note: 'La combinación de estos caracteres forma las identidades sociales: 先 (antes) + 生 (nacer/vida) = 先生 (Profesor: quien nació antes que tú).',
        objective: 'Comprender la lógica etimológica de los roles humanos y jerarquías en kanji.',
      },
      {
        id: 'm7l5',
        t: 'Tiempo y Espacio (今, 年, 時, 分, 何, 国)',
        s: 'kon · nen · ji · fun · nan · koku',
        xp: 80,
        chars: ['今', '年', '時', '分', '何', '国'],
        reads: ['kon', 'nen', 'ji', 'fun', 'nan', 'koku'],
        vocab: [
          { jp: 'きょう', es: 'Hoy (Día presente)' },
          { jp: 'ことし', es: 'Este año' },
          { jp: 'なんじ です か', es: '¿Qué hora es?' },
          { jp: 'がいこく', es: 'País extranjero' },
        ],
        note: '今 (ahora/presente), 年 (año), 時 (tiempo/hora), 分 (minuto/dividir), 何 (qué), 国 (país delimitado por fronteras).',
        objective: 'Leer sinogramas temporales y geográficos en textos formales.',
      },
      {
        id: 'm7l6',
        t: 'Compuestos Jukugo N5 de Alto Rendimiento',
        s: 'nihon · sensei · gakusei · nihonjin · kyou · kotoshi',
        xp: 100,
        chars: ['日本', '先生', '学生', '日本人', '今日', '今年', '何時'],
        reads: ['nihon', 'sensei', 'gakusei', 'nihonjin', 'kyou', 'kotoshi', 'nanji'],
        vocab: [
          { jp: 'わたし は にほんじん です', es: 'Yo soy japonés' },
          { jp: 'せんせい は きょう きます', es: 'El profesor viene hoy' },
          { jp: 'ことし にほん へ いきます', es: 'Este año iré a Japón' },
        ],
        note: 'Jukugo (熟語) son palabras compuestas por 2 o más kanji. El 70% del vocabulario formal japonés se lee mediante la combinación de sinogramas.',
        objective: 'Leer fluidamente palabras compuestas reales de uso diario sin asistencia de furigana.',
      },
    ],
  },
  {
    id: 'm8',
    levelNum: 6,
    levelTitle: 'Nivel 6: Lectura, Pragmática e Inmersión',
    block: 'VI',
    bLabel: 'Fluidez y Comunicación Real',
    title: 'Módulo 8',
    sub: 'Forma TE · Transitividad · Conectores · Keigo',
    color: '#E24A7A',
    xpE: 450,
    req: 'm7',
    lessons: [
      {
        id: 'm8l1',
        t: 'La Forma TE (〜て) y Peticiones de Cortesía',
        s: 'tabete · nonde · itte · mite · matte · kudasai',
        xp: 90,
        chars: ['たべて', 'のんで', 'いって', 'みて', 'まって', 'ください'],
        reads: ['tabete', 'nonde', 'itte', 'mite', 'matte', 'kudasai'],
        vocab: [
          { jp: 'ちょっと まって ください', es: 'Por favor espere un momento' },
          { jp: 'これ を みて ください', es: 'Por favor mire esto' },
          { jp: 'すし を たべて ください', es: 'Por favor coma sushi' },
        ],
        note: 'La forma TE es la navaja suiza de la gramática japonesa. Conecta verbos en secuencia y con KUDASAI forma peticiones amables: [Forma Te] + ください.',
        objective: 'Solicitar acciones amables y encadenar secuencias de eventos en tiempo presente.',
      },
      {
        id: 'm8l2',
        t: 'Acción Continua (〜ています)',
        s: 'tabete imasu · benkyou shite imasu · mite imasu',
        xp: 80,
        chars: ['たべて', 'のんで', 'みて', 'います', 'べんきょう'],
        reads: ['tabete', 'nonde', 'mite', 'imasu', 'benkyou'],
        vocab: [
          { jp: 'いま ごはん を たべて います', es: 'Ahora estoy comiendo' },
          { jp: 'にほんご を べんきょう して います', es: 'Estoy estudiando japonés' },
          { jp: 'アニメ を みて います', es: 'Estoy viendo anime' },
        ],
        note: 'Forma TE + IMASU expresa la acción que está ocurriendo en este instante ("estoy comiendo", "estoy estudiando") o estados continuos resultantes.',
        objective: 'Describir actividades en progreso en tiempo real y estados duraderos.',
      },
      {
        id: 'm8l3',
        t: 'Transitividad (Jidoushi vs Tadoushi)',
        s: 'aku / akeru · shimaru / shimeru · kieru / kesu',
        xp: 90,
        chars: ['あく', 'あける', 'しまる', 'しめる', 'きえる', 'けす'],
        reads: ['aku', 'akeru', 'shimaru', 'shimeru', 'kieru', 'kesu'],
        vocab: [
          { jp: 'まど が あく', es: 'La ventana se abre (sola, intransitivo con GA)' },
          { jp: 'まど を あける', es: 'Abro la ventana (yo actúo sobre ella con WO)' },
          { jp: 'でんき を けす', es: 'Apago la luz (transitivo)' },
        ],
        note: 'Jidoushi (intransitivo) = la acción ocurre sola, sin agente explícito (usa が). Tadoushi (transitivo) = una persona actúa sobre el objeto (usa を).',
        objective: 'Diferenciar acciones automáticas de la naturaleza frente a acciones ejecutadas con intención humana.',
      },
      {
        id: 'm8l4',
        t: 'Habla Coloquial y Contracciones de Anime',
        s: 'tabeteru · wakannai · janai · ne · yo',
        xp: 80,
        chars: ['たべてる', 'たべている', 'わかんない', 'わからない'],
        reads: ['tabeteru', 'tabeteiru', 'wakannai', 'wakaranai'],
        vocab: [
          { jp: 'なに を たべてる の', es: '¿Qué estás comiendo? (coloquial)' },
          { jp: 'ぜんぜん わかんない', es: 'No entiendo nada (coloquial anime)' },
          { jp: 'それ は ちがう よ', es: '¡Eso no es así! (partícula de énfasis YO)' },
        ],
        note: 'El japonés real de la calle y del anime contrae las formas largas: Tabete iru → Tabeteru, Wakaranai → Wakannai. Dominar esto evita el choque auditivo con el habla nativa.',
        objective: 'Reconocer y comprender contracciones coloquiales y partículas finales de matiz discursivo (NE, YO).',
      },
      {
        id: 'm8l5',
        t: 'Conectores Lógicos y Tadoku (Lectura Fluida)',
        s: 'dakara · shikashi · nazenara · tsumari · tatoeba',
        xp: 90,
        chars: ['だから', 'しかし', 'なぜなら', 'つまり', 'たとえば'],
        reads: ['dakara', 'shikashi', 'nazenara', 'tsumari', 'tatoeba'],
        vocab: [
          { jp: 'だから わたし は べんきょう します', es: 'Por eso / por lo tanto yo estudio' },
          { jp: 'しかし それ は ちがいます', es: 'Sin embargo, eso no es así' },
          { jp: 'つまり かれ は ヒーロー です', es: 'En resumen, él es un héroe' },
        ],
        note: 'Los conectores lógicos estructuran el pensamiento en párrafos largos: DAKARA (por eso), SHIKASHI (sin embargo), NAZENARA (porque), TSUMARI (en resumen), TATOEBA (por ejemplo).',
        objective: 'Comprender la cohesión de ensayos y textos extensos sin necesidad de traducir palabra por palabra.',
      },
      {
        id: 'm8l6',
        t: 'Pragmática Social y Keigo (Cortesía y Negocios)',
        s: 'arigatou gozaimasu · sumimasen · irasshaimase · itadakimasu · otsukaresama',
        xp: 100,
        chars: ['いらっしゃいませ', 'いただきます', 'ごちそうさまでした', 'おつかれさまでした', 'まいります'],
        reads: ['irasshaimase', 'itadakimasu', 'gochisousamadeshita', 'otsukaresamadeshita', 'mairimasu'],
        vocab: [
          { jp: 'いただきます', es: 'Buen provecho (agradezco humildemente la comida)' },
          { jp: 'ごちそうさまでした', es: 'Gracias por la comida (al terminar)' },
          { jp: 'おつかれさまでした', es: 'Buen trabajo / gracias por su esfuerzo' },
        ],
        note: 'Keigo y fórmulas sociales sagradas: Irasshaimase (bienvenido), Itadakimasu (respeto a la vida antes de comer), Gochisousama (agradecimiento al anfitrión), Otsukaresama (reconocimiento laboral mutuo).',
        objective: 'Interactuar con impecable cortesía y respeto social en la sociedad japonesa moderna.',
      },
    ],
  },
];
